### ISSUE TITLE
How to? Renew letsencrypt plesk certificate via cronjob

### ISSUE THREAD

**Issue by geschke-eu** [plesk/letsencrypt-plesk#10]
Hi everyone,

First of all: Great work! I'm really happy we will get an let's encrypt plesk plugin!
But to get it automated in the most convenient way, I would like to give the renewal task to a cronjob.

I tried to make it work using letsencrypt-plesk plugin directly:
`./letsencrypt-auto --renew-by-default --letsencrypt-plesk -d [my_domain]`

But it doesnt work, says it needs some sort of secret key?
`letsencrypt: error: argument --letsencrypt-plesk:plesk-secret-key: expected one argument`

So i tried further on and was able to set up a certificate using webroot-plugin:
`$ ./letsencrypt-auto --renew-by-default --webroot  -w /var/www/vhosts/[my_location] -d [my_domain]`
Works all fine, and it does create the certificate and will give me a blue promt asking, if I would like to install it to apache or plesk. If i choose plesk, it works.

Is there any way to extend my command so it doesn't show that promt and automatically chooses plesk-installation, so I can use it for a cronjob? Or can someone explain to me, what kind of secret key it needs and how to use it?

Thanks in advance!

**Comment by xgin** [comment]
Hey @geschke-eu, arguments `--authenticator letsencrypt-plesk:plesk --installer letsencrypt-plesk:plesk` could be used for automation.

The secret key is an API authentication ([doc](http://docs.plesk.com/en-US/12.5/cli-linux/using-command-line-utilities/secret_key-authentication-in-the-xml-api-service.73880/)), but this is optional argument - it is created on demand while executing with root privileges.

BTW, try [the extension](https://ext.plesk.com/packages/f6847e61-33a7-4104-8dc9-d26a0183a8dd-letsencrypt) - it creates the cronjob after the installation.

**Comment by mrclschstr** [comment]
@xgin The cronjob is an excellent feature, thank you!

**Comment by ntimo** [comment]
@xgin Where can I see this cronjob from the extention in plesk?

**Comment by mrclschstr** [comment]
@ntimo Server Management > Tools & Settings > Scheduled Tasks

**Comment by geschke-eu** [comment]
Hey @xgin, thanks for your reply! Your arguments worked like a charm :+1: 

Also, it's pretty cool that we have a plesk plugin for UI now. Thanks for all your awesome work!

But I guess, i will use the command line option to go on, because we need some script automation in setting up domain/website instances anyway. 

I would close the Issue, but maybe anyone can help me with the second promt, which is asking if I would like to set a redirect, so that everyone has to use HTTPS. How can I pre-set this to "easy" via argument? Found nothing in the help...

Thanks @ all!

**Comment by xgin** [comment]
@geschke-eu create a separate issue about the redirect enhancement.

**Comment by geschke-eu** [comment]
Ok, I'll do. Thanks!

**Comment by TeHashX** [comment]
I saw that the certificate is renewed every month in cronjob, shouldn't be every 90 days?

**Comment by xgin** [comment]
@TeHashX there is a note here https://letsencrypt.readthedocs.org/en/latest/using.html#renewal
> make it less than every 90 days to avoid problems, say every month

**Comment by TeHashX** [comment]
Cronjob is created automatically by the script, I'm not sure if this is correct for every 88 days?
* * *88 * *
