### ISSUE TITLE
Option to secure plesk-panel isn't shown

### ISSUE THREAD

**Issue by Ninerian** [plesk/letsencrypt-plesk#100]
Hello,

actually the option to secure the plesk panel with the domain certificate isn't shown for me. I reinstalled the extension yesterday. Is there any settings which could prevent this?

**Comment by stayallive** [comment]
You have to make sure you access Plesk via the same domain you are trying to secure.

If your Plesk you are trying to secure runs on `https://plesk01.domain.com:8443` you need to access the Plesk panel through that url and create a domain/subdomain for `plesk01.domain.com` and then request a certificate for that domain/subdomain the option will show there.

**Comment by Ninerian** [comment]
Thank your for this information. Now it work.
