### ISSUE TITLE
err_cert_authority_invalid error on Android browsers

### ISSUE THREAD

**Issue by CoskunSunali** [plesk/letsencrypt-plesk#102]
I have some certificates that have been generated using Plesk's Lets Encrypt extension.

The certificates work fine on desktop browsers as well as browsers running on iOS 9.3.x.

However, both the Samsung's Internet app and Google's Chrome app on Android throw the following exception when a site is visited.

It is an Android phone (Samsung S7 edge) running on Android M 6.0.1.

What do you think could be a possible reason for the exceptions being thrown?

![screenshot_20160525-031010](https://cloud.githubusercontent.com/assets/6509380/15523995/3db9c094-2227-11e6-980d-983a8debfca3.png)
![screenshot_20160525-031016](https://cloud.githubusercontent.com/assets/6509380/15523996/3dba5824-2227-11e6-89e6-1cfb15a86958.png)
![screenshot_20160525-031001](https://cloud.githubusercontent.com/assets/6509380/15523997/3dbc01d8-2227-11e6-87f9-0488e7261cbe.png)

**Comment by CoskunSunali** [comment]
Seems that Firefox for Windows throws an exception as well. Please see the details:

```
codinq.com uses an invalid security certificate.

The certificate is not trusted because the issuer certificate is unknown.

The server might not be sending the appropriate intermediate certificates.

An additional root certificate may need to be imported.

Error code: SEC_ERROR_UNKNOWN_ISSUER

https://codinq.com/

Peer's Certificate issuer is not recognized.

HTTP Strict Transport Security: false
HTTP Public Key Pinning: false

Certificate chain:

-----BEGIN CERTIFICATE-----
MIIFCDCCA/CgAwIBAgISA5dKbX1MUm70PzYGQL6IC7tNMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xNjA1MjQyMzAxMDBaFw0x
NjA4MjIyMzAxMDBaMBUxEzARBgNVBAMTCmNvZGlucS5jb20wggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQC5hWPRGxy03e8avBwRruRpiQI0gjAq6wQAuuog
7I0pUSt4O8AgZRwCVZU/9zyGfJGnXXr7BlmLMlr3x3klu9mTD0CKDAo38z38vgPv
jt8wSTCrc+ck3fqkoo+RiGJ5c2W5jyQbCWwmYqfK47ZBDi3t0YavQVIs8p2M7wbj
xz9uYferN7se4Pq86lcksF2rMV6XByxnkOPsl250t3s9r/LKEoPXwH7acUH4CY7d
JCK/YfkRjehUclB+ZSzTrXJCBPVxWYqu8VwgCWIbXBUsi8Z0pabzxGcoWJqE6l6l
DJ4gDZfj33QMus8k83MVOoIcuDem7HH+7Q0iSC/9dTKHg/NlAgMBAAGjggIbMIIC
FzAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
MAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFCtIlnmO1ctZMZm8inX2WhUGBK2pMB8G
A1UdIwQYMBaAFKhKamMEfd265tE5t6ZFZe/zqOyhMHAGCCsGAQUFBwEBBGQwYjAv
BggrBgEFBQcwAYYjaHR0cDovL29jc3AuaW50LXgzLmxldHNlbmNyeXB0Lm9yZy8w
LwYIKwYBBQUHMAKGI2h0dHA6Ly9jZXJ0LmludC14My5sZXRzZW5jcnlwdC5vcmcv
MCUGA1UdEQQeMByCCmNvZGlucS5jb22CDnd3dy5jb2RpbnEuY29tMIH+BgNVHSAE
gfYwgfMwCAYGZ4EMAQIBMIHmBgsrBgEEAYLfEwEBATCB1jAmBggrBgEFBQcCARYa
aHR0cDovL2Nwcy5sZXRzZW5jcnlwdC5vcmcwgasGCCsGAQUFBwICMIGeDIGbVGhp
cyBDZXJ0aWZpY2F0ZSBtYXkgb25seSBiZSByZWxpZWQgdXBvbiBieSBSZWx5aW5n
IFBhcnRpZXMgYW5kIG9ubHkgaW4gYWNjb3JkYW5jZSB3aXRoIHRoZSBDZXJ0aWZp
Y2F0ZSBQb2xpY3kgZm91bmQgYXQgaHR0cHM6Ly9sZXRzZW5jcnlwdC5vcmcvcmVw
b3NpdG9yeS8wDQYJKoZIhvcNAQELBQADggEBAHohS4+E8xTHTAnsEPZqvjka0+8V
M4rnNw4+O1A+Kiq18A76HiCjLf1FE6AlYgtq3BUsBK/EZJ0b0lAyJ66/ZmXvxH/e
cXbsR1KwrM+RXxvYBpxHZxiuLULDKNUfU3nt9nDKkOwlSlqpmVvQlcdP/sd8Ue8s
UzxUk19QKdfLCm2d1mDDjgEwk9L9PvtYuNqINjmas2zN7+VsrZ0JX+8UcgYyH8mG
wNxi/M+rUNcD37IgYU6TXH7Ef+1Ca8dEWe8L6fkvOq/5RWxkD9Ki2T3olJIfFto7
GruDAlGqdJaP3nBy3QO0E8WbJEPq3TGz16N6WSCVaOshsGXSPzzCpVl7iIY=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEqDCCA5CgAwIBAgIRAJgT9HUT5XULQ+dDHpceRL0wDQYJKoZIhvcNAQELBQAw
PzEkMCIGA1UEChMbRGlnaXRhbCBTaWduYXR1cmUgVHJ1c3QgQ28uMRcwFQYDVQQD
Ew5EU1QgUm9vdCBDQSBYMzAeFw0xNTEwMTkyMjMzMzZaFw0yMDEwMTkyMjMzMzZa
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAJzTDPBa5S5Ht3JdN4OzaGMw6tc1Jhkl4b2+NfFwki+3uEtB
BaupnjUIWOyxKsRohwuj43Xk5vOnYnG6eYFgH9eRmp/z0HhncchpDpWRz/7mmelg
PEjMfspNdxIknUcbWuu57B43ABycrHunBerOSuu9QeU2mLnL/W08lmjfIypCkAyG
dGfIf6WauFJhFBM/ZemCh8vb+g5W9oaJ84U/l4avsNwa72sNlRZ9xCugZbKZBDZ1
gGusSvMbkEl4L6KWTyogJSkExnTA0DHNjzE4lRa6qDO4Q/GxH8Mwf6J5MRM9LTb4
4/zyM2q5OTHFr8SNDR1kFjOq+oQpttQLwNh9w5MCAwEAAaOCAZIwggGOMBIGA1Ud
EwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgGGMH8GCCsGAQUFBwEBBHMwcTAy
BggrBgEFBQcwAYYmaHR0cDovL2lzcmcudHJ1c3RpZC5vY3NwLmlkZW50cnVzdC5j
b20wOwYIKwYBBQUHMAKGL2h0dHA6Ly9hcHBzLmlkZW50cnVzdC5jb20vcm9vdHMv
ZHN0cm9vdGNheDMucDdjMB8GA1UdIwQYMBaAFMSnsaR7LHH62+FLkHX/xBVghYkQ
MFQGA1UdIARNMEswCAYGZ4EMAQIBMD8GCysGAQQBgt8TAQEBMDAwLgYIKwYBBQUH
AgEWImh0dHA6Ly9jcHMucm9vdC14MS5sZXRzZW5jcnlwdC5vcmcwPAYDVR0fBDUw
MzAxoC+gLYYraHR0cDovL2NybC5pZGVudHJ1c3QuY29tL0RTVFJPT1RDQVgzQ1JM
LmNybDATBgNVHR4EDDAKoQgwBoIELm1pbDAdBgNVHQ4EFgQUqEpqYwR93brm0Tm3
pkVl7/Oo7KEwDQYJKoZIhvcNAQELBQADggEBANHIIkus7+MJiZZQsY14cCoBG1hd
v0J20/FyWo5ppnfjL78S2k4s2GLRJ7iD9ZDKErndvbNFGcsW+9kKK/TnY21hp4Dd
ITv8S9ZYQ7oaoqs7HwhEMY9sibED4aXw09xrJZTC9zK1uIfW6t5dHQjuOWv+HHoW
ZnupyxpsEUlEaFb+/SCI4KCSBdAsYxAcsHYI5xxEI4LutHp6s3OT2FuO90WfdsIk
6q78OMSdn875bNjdBYAqxUp2/LEIHfDBkLoQz0hFJmwAbYahqKaLn73PAAm1X2kj
f1w8DdnkabOLGeOVcj9LQ+s67vBykx4anTjURkbqZslUEUsn2k5xeua2zUk=
-----END CERTIFICATE-----
```

**Comment by xgin** [comment]
Hey @CoskunSunali 
Take a look at the similar topic https://community.letsencrypt.org/t/cert-for-chimpquote-com-failing-on-android-phones/13544/14

They say it is an issue in IIS:
> When you issued a new certificate, it would have been an LE X3 and windows IIS tends to cache the old X1 certificate. the link [How to clear the CryptNet cache in Windows](https://unmitigatedrisk.com/?p=23) should help hopefully.

**Comment by Fogetti** [comment]
I have the same issue on Android. My website https://fogetti.com looks completely fine on iOS and desktop browsers. But it throws NET::ERR_CERT_AUTHORITY_INVALID on Android.

**Comment by xgin** [comment]
@Fogetti 
The certificate on your website does not contain a full chain:
https://www.sslshopper.com/ssl-checker.html#hostname=fogetti.com
It says only server certificate is supplied, but intermediate certificate is also required for some browsers.

Do I understand you correctly that you do not have Plesk installed on your server?

**Comment by CoskunSunali** [comment]
Hey @xgin,

Thank you for your response. I checked the link you shared, cleared the CryptNet cache and also cleared all the trusted Let's Encrypt certificates from the store but still no chance.

The X1 somehow keeps coming back. 

Please see the broken chain: https://www.sslshopper.com/ssl-checker.html#hostname=codinq.com

Also please see the attached screenshot:

![cert](https://cloud.githubusercontent.com/assets/6509380/16656742/7f7152be-4468-11e6-9971-c527c4c1a9e1.png)

**Comment by CoskunSunali** [comment]
@xgin,

Please ignore my previous comment's notification (I just deleted it.)

Seems that I missed an item from the instructions you shared.

Following them strictly has helped and things work like a charm now.

Thank you for your assistance!

**Comment by xgin** [comment]
Good to hear the problem is solved.

Hope it won't occur any more since X3 authority has been issuing certificates for several months.

**Comment by Fogetti** [comment]
@xgin Thanks. You were right. I didn't provide the full chain to the client. Providing the full chain solved it. And yes, I don't have Plesk on my server.

**Comment by mariozanchet** [comment]
I have the same issue too. My website https://www.ondehospedar.com.br looks completely fine on desktop browsers. But not on Andriod.

**Comment by danger89** [comment]
Same issue today with cloud.melroy.org at other subdomains. My server was working in the past just fine. Bug the organization is called 'Fortinet' instead of Let's Encrypt in the certificate under Android. Under Firefox on the desktop PC it just looks fine and works good, I'm also using the chain file correctly.

https://www.sslshopper.com/ssl-checker.html#hostname=cloud.melroy.org (Check is OK!)

**Android:**
![photo_2017-10-23_12-36-35](https://user-images.githubusercontent.com/628926/31884861-da5c6c90-b7ee-11e7-90f9-1ad5866d1f5b.jpg)

![photo_2017-10-23_12-36-38](https://user-images.githubusercontent.com/628926/31884860-da0e948e-b7ee-11e7-9ac6-cd79049f1f68.jpg)

**Firefox (Windows):**
![afbeelding](https://user-images.githubusercontent.com/628926/31884892-ffb4c6ea-b7ee-11e7-82fd-521c9b6bab30.png)

I don't get it! What is going wrong?
