### ISSUE TITLE
ConnectionError: ('Connection aborted.', error(10054, 

### ISSUE THREAD

**Issue by LaForge112** [plesk/letsencrypt-plesk#103]
[letsencrypt3.txt](https://github.com/plesk/letsencrypt-plesk/files/286956/letsencrypt3.txt)
Hi letsencrypt-plesk developers,

im always getting error:

` Fehler: Fehler bei der Installation des SSL-Zertifikats von Let's Encrypt: Failed letsencrypt execution: An unexpected error occurred:
ConnectionError: ('Connection aborted.', error(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen'))
Please see the logfiles in C:\Program Files (x86)\Parallels\Plesk\var\modules\letsencrypt\logs for more details.`

I'm using plesk win 12.5.30 MU 33 on Windows Server 2012 R2
First i thought it's an DNS problem because Domains an DNS are external hosted with pointing on Server IP. (V4 an V6)

After all it tries to connect to 127.0.0.1 and then breaks as i understand the log. 

logfile is attached. Maybe someone can solve this problem.

Many thanks at this time.

Greets LaForge

**Comment by xgin** [comment]
Hey @LaForge112 
Thank you for reporting the issue.
We also experience the problem in our testing environment.
It seems a Windows-specific issue with SNI.
We are investigating and I hope a solution will be found soon.

**Comment by LaForge112** [comment]
Hi @xgin,

Thank u for your answer.
could I help Somehow?

Greets LaForge112

**Comment by LaForge112** [comment]
Sadly i have to post again. As i saw in changes.md the error should be fixed in 0.1.7 as well 0.1.8 is in the making.

but in 0.1.7 the error occurs again.

```
Fehler: Fehler bei der Installation des SSL-Zertifikats von Let's Encrypt: Failed letsencrypt execution: An unexpected error occurred:
ConnectionError: ('Connection aborted.', error(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen'))
Please see the logfiles in C:\Program Files (x86)\Parallels\Plesk\var\modules\letsencrypt\logs for more details.
```

Log shows similar to previous version. I can post if you want.

Greets LaForge112

**Comment by xgin** [comment]
@LaForge112, sorry to hear that.
Try to remove the directory `C:\Program Files (x86)\Parallels\Plesk\var\modules\letsencrypt\venv` and install the extension again.
That will ensure the latest packages are installed.
If it wont work, post the log file please.

**Comment by LaForge112** [comment]
@xgin Hmmm be not too sorry, as it seems no one else has this problem. Reinstalling  i did before. But now once again with deleting the Folder. But nothing changed. So here's the log. Hopefully you can help me again. 
Thank you so much. 
[letsencrypt4.txt](https://github.com/plesk/letsencrypt-plesk/files/450441/letsencrypt4.txt)


LaForge112

**Comment by LaForge112** [comment]
@xgin Update: After installing 0.1.8 unfortunately nothing changed. Same error as always.
Thank you again for your help.

**Comment by toliphant** [comment]
@LaForge112 , I am getting the same error you are getting.

**Comment by LaForge112** [comment]
Whatever you've done. Tested today an now it works.

Greets LaFo

**Comment by toliphant** [comment]
@LaForge112 Lucky you. I am still getting the same error. I noticed plesk has pushed out some updates but hasn't changed anything on my end.

**Comment by xgin** [comment]
@LaForge112 awesome!
Python was updated to the version 2.7.11 in the microupdate#48
@toliphant could you please check it has been already installed?

**Comment by toliphant** [comment]
@xgin I can confirm that plesk was updated. Are there any particular settings that need to be set up or is it a matter of install the Let's Encrypt extension and then create a domain and run the extension? We do have Let's Encrypt installed manually on the server (which does work but would be easier to handle with the click of a button rather than command line) before we started to use Plesk to manage our clients. It still seems to be getting stuck on this line...

requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): 127.0.0.1

From here it looks like it fails and prints a stack trace in the log.

**Comment by toliphant** [comment]
@LaForge112 @xgin Do you know if the dns has to be handled through plesk also for this to work? Currently we are handling all our dns through our hosting provider admin. Thanks.

**Comment by toliphant** [comment]
The extension is working fine. We had some binding issues on the server. After that was fixed it was able to issue certs just fine.

**Comment by LaForge112** [comment]
@toliphant My DNS is external too, as u see in posts above. But it seems now working for you too, also with external DNS?

**Comment by toliphant** [comment]
@LaForge112 Yes it is working smoothly now. The external DNS wasn't causing any issue, it was the https binding on plesk in IIS.

**Comment by Riedi2070** [comment]
@toliphant Could you give some information about issue? What do you have done with the https binding on plesk in IIS?
