### ISSUE TITLE
Issue in parallel plesk

### ISSUE THREAD

**Issue by sajeena123** [plesk/letsencrypt-plesk#108]
I have installed letsencrypt-plesk, but getting an error like 

> This operation is taking too long. Check the results in a few minutes

Anybody has any idea ?

**Comment by xgin** [comment]
Please check the log file `/usr/local/psa/var/modules/letsencrypt/logs/letsencrypt.log`
What is the last record there?

**Comment by xgin** [comment]
In the latest version 1.7 of the extension we use `--non-interactive` flag, that should prevent hanging (waiting for input) and properly report errors.
Please, check the issue again and feel free to reopen.
