### ISSUE TITLE
ContextualVersionConflict: (cryptography 1.3.1), Requirement.parse('cryptography>=1.3.4'), set(['PyOpenSSL']))

### ISSUE THREAD

**Issue by jtokic** [plesk/letsencrypt-plesk#117]
Error: Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: Traceback (most recent call last):
File "/usr/local/psa/var/modules/letsencrypt/venv/bin/certbot", line 11, in <module>
sys.exit(main())
File "/usr/local/psa/var/modules/letsencrypt/venv.sIXBk/lib/python2.7/site-packages/certbot/main.py", line 700, in main
plugins = plugins_disco.PluginsRegistry.find_all()
File "/usr/local/psa/var/modules/letsencrypt/venv.sIXBk/lib/python2.7/site-packages/certbot/plugins/disco.py", line 174, in find_all
plugin_ep = PluginEntryPoint(entry_point)
File "/usr/local/psa/var/modules/letsencrypt/venv.sIXBk/lib/python2.7/site-packages/certbot/plugins/disco.py", line 33, in __init__
self.plugin_cls = entry_point.load()
File "/usr/local/psa/var/modules/letsencrypt/venv.sIXBk/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2280, in load
self.require(*args, **kwargs)
File "/usr/local/psa/var/modules/letsencrypt/venv.sIXBk/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in require
items = working_set.resolve(reqs, env, installer)
File "/usr/local/psa/var/modules/letsencrypt/venv.sIXBk/lib/python2.7/site-packages/pkg_resources/__init__.py", line 858, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (cryptography 1.3.1 (/usr/local/psa/var/modules/letsencrypt/venv.sIXBk/lib/python2.7/site-packages), Requirement.parse('cryptography>=1.3.4'), set(['PyOpenSSL']))

**Comment by mossmane** [comment]
Got exactly the same problem i tried every known solution but it always failed

**Comment by Lloyd1978** [comment]
Yeah +1, I installed on a clients server earlier got the same error. Ubuntu 14.04.5 LTS

**Comment by dailyhypervisor** [comment]
Same here.  I installed it earlier this morning and am seeing the same issue on Centos 6.8.  There error is verbatim what is posted.  I have searched just about everything I can think of and cannot find any solution that works.  It appears to be an issue with the cryptography, but one of the solutions I have found solve the issue.  Please help......

**Comment by dailyhypervisor** [comment]
This is the error I see when trying to upgrade the cryptography:

  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
Failed to build cryptography
Installing collected packages: cffi, cryptography
  Found existing installation: cffi 1.5.2
    Uninstalling cffi-1.5.2:
      Successfully uninstalled cffi-1.5.2
  Found existing installation: cryptography 1.3.1
    Uninstalling cryptography-1.3.1:
      Successfully uninstalled cryptography-1.3.1
  Running setup.py install for cryptography ... error
    Complete output from command /usr/local/psa/var/modules/letsencrypt/venv.W9Q9i/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kqimzt/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-iN67yf-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/psa/var/modules/letsencrypt/venv.W9Q9i/include/site/python2.7/cryptography:

**Comment by dailyhypervisor** [comment]
Plesk 12.5.30, CentOS 6.8, Python 2.6.6

**Comment by AndreasBeyer** [comment]
Same Problem
12.5.30 Update #44, Ubuntu 14.04.5‬, Python 2.7.6

**Comment by xgin** [comment]
The 3d-party package PyOpenSSL has been released: https://pyopenssl.readthedocs.io/en/stable/changelog.html#id1

Workaround to install the previous version:
```
/usr/local/psa/var/modules/letsencrypt/venv/bin/pip install pyopenssl==16.0.0
```
