### ISSUE TITLE
Is there a way to use 4096 Bit keysize?

### ISSUE THREAD

**Issue by holzhannes** [plesk/letsencrypt-plesk#12]
Hey there!
Thank you very much for this Extension. Is there a way to use 4096 bit keys instead of 2048 Bit?

**Comment by xgin** [comment]
Yeah!
Create [the configuration file](https://letsencrypt.readthedocs.org/en/latest/using.html#configuration-file) `/usr/local/psa/var/modules/letsencrypt/cli.ini` with the content `rsa-key-size = 4096`
I suppose this option is not required in UI, and one time configuration is enough.

**Comment by holzhannes** [comment]
Thank you! Tested and working!
