### ISSUE TITLE
Warning when running command: certbot.client:Non-standard path(s)

### ISSUE THREAD

**Issue by devanes** [plesk/letsencrypt-plesk#123]
When I run the cli command, I regularly get the following warning:
`WARNING:certbot.client:Non-standard path(s), might not work with crontab installed by your operating system package manager`

**Comment by UFHH01** [comment]
A Plesk Forum - User experienced the same issue as described and solved it by using:

`1: apt-get update
2: apt-get upgrade
3: plesk installer --select-release-current --reinstall-patch --upgrade-installed-components`

Reference: => https://talk.plesk.com/threads/letsencrypt-issue.339493/#post-809150

**Comment by xgin** [comment]
Not actual since version 2.0
