### ISSUE TITLE
Connection aborted, error 10054

### ISSUE THREAD

**Issue by PIXPOINT** [plesk/letsencrypt-plesk#128]
Hello,
I always get this error. I have already installed the extension again.

ERROR:
> Fehler: Fehler bei der Installation des SSL-Zertifikats von Let's Encrypt: Failed letsencrypt execution: Saving debug log to C:\Program Files (x86)\Parallels\Plesk\var\modules\letsencrypt\logs\letsencrypt.log
>  Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
>  Obtaining a new certificate
>  Performing the following challenges:
>  http-01 challenge for www.xxxxxxx.com
>  Starting new HTTPS connection (1): 127.0.0.1
>  Cleaning up challenges
>  An unexpected error occurred:
>  ConnectionError: ('Connection aborted.', error(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen'))
>  Please see the logfiles in C:\Program Files (x86)\Parallels\Plesk\var\modules\letsencrypt\logs for more details.

I have Plesk 12.5 and Windows Server 2012 R2 and Letsencrypt-Plesk 1.9
can someone help me?

**Comment by xgin** [comment]
Take a look at #103 
Do you have the latest Plesk update installed? AFAIK # 50

**Comment by PIXPOINT** [comment]
Yes I have instaled the last updats. Update. #103 was not helpful :-/

**Comment by PIXPOINT** [comment]
Hey, problem solved by upgrading to **Plesk Onyx 17.0.17 Update Nr. 3**

**Comment by Riedi2070** [comment]
I have installed Plesk Onyx 17.0.17 Update Nr. 14, but I have the same problem.
