### ISSUE TITLE
plesk extension on removal / install

### ISSUE THREAD

**Issue by djdesign** [plesk/letsencrypt-plesk#130]
On a fresh install of plugin 1.9-2, with Plesk 17.0.17 running on CentOS 6.8, got the following errors. 
Please advise on steps needed to resolve this?

Removal
```
Error: The extension Let's Encrypt was removed with errors:
Execution of /usr/local/psa/admin/plib/modules/letsencrypt/scripts/pre-uninstall.php failed with exit code 1 and the output:
[2016-10-31 17:42:02] ERR [extension/letsencrypt] Cannot uninstall scheduled task renew_certificates with error: Object not found: 0x
[2016-10-31 17:42:02] ERR [panel] Execution le-installer has failed with exit code 126, stdout: , stderr: sh: /usr/local/psa/admin/bin/modules/letsencrypt/le-installer: Permission denied
:
0: /usr/local/psa/admin/plib/pm/ApiCli.php:150
	pm_ApiCli::_filterResult(string 'le-installer', integer '126', string '', string 'sh: /usr/local/psa/admin/bin/modules/letsencrypt/le-installer: Permission denied
', integer '5')
1: /usr/local/psa/admin/plib/pm/ApiCli.php:143
	pm_ApiCli::_execCommand(string 'le-installer', string ''/usr/local/psa/admin/bin/modules/letsencrypt/le-installer'  'remove'', integer '5', array)
2: /usr/local/psa/admin/plib/pm/ApiCli.php:91
	pm_ApiCli::callSbin(string 'le-installer', array)
3: /usr/local/psa/admin/plib/modules/letsencrypt/library/Installer.php:96
	Modules_Letsencrypt_Installer::cleanup()
4: /usr/local/psa/admin/plib/modules/letsencrypt/scripts/pre-uninstall.php:6
ERROR: pm_Exception_ResultException: Execution le-installer has failed with exit code 126, stdout: , stderr: sh: /usr/local/psa/admin/bin/modules/letsencrypt/le-installer: Permission denied
 (ApiCli.php:150)
```
Fresh Install
```
Error: Unable to install the extension:
Execution of /usr/local/psa/admin/plib/modules/letsencrypt/scripts/post-install.php failed with exit code 1 and the output:
```

**Comment by xgin** [comment]
Could you specify your OS
Please, take a look at the similar issue #22

**Comment by djdesign** [comment]
Updated Initial post.
OS version CentOS 6.8

**Comment by xgin** [comment]
The document root of your domain seems misconfigured in Plesk:
`www_root` equals to `/var/www/vhosts/thedjdesign.com/willitzer.com`
and there are `additional-settings`:
```
ServerName willitzer.com
DocumentRoot /var/www/vhosts/thedjdesign.com/willitzer.com/bedrock/web
...
```
That overrides Plesk directives and the document root is defined incorrectly.
Propose to remove `additional-settings` and `additional-ssl-settings` in `Apache & nginx settings` under the domain. And properly set `Document root` in `Hosting settings` equal to `willitzer.com/bedrock/web`

**Comment by djdesign** [comment]
@xgin thank you for the input. 

Setting the Document Root properly thought Plesk is the right path to take, which in this case resolved my issues.

last question if I was to include a file in the additional-nginx-directives:
`include $www_root/path-to-file/file.conf`
not
`include /var/www/vhosts/domain.com/path-to-file/file.conf`

Would that be the right way to go about that instead of the absolute path?

Thank you.

**Comment by xgin** [comment]
Nope, `include` directives are processed on server start and variables substitution is not allowed.

Plesk configs could be customised in different ways:

- https://docs.plesk.com/en-US/17.0/advanced-administration-guide-linux/virtual-hosts-configuration/changing-virtual-hosts-settings-using-configuration-templates.68693/
- If you create the config template `/var/www/vhosts/.skel/0/conf/vhost_nginx.conf` then a new domain will use it as `additional-nginx-directives` and the substitution of `@domain_name@` is allowed here.

Anyway, this question is not related to the extension. Feel free to ask the question on the forum https://talk.plesk.com/
