### ISSUE TITLE
Support for IDN

### ISSUE THREAD

**Issue by t0b3** [plesk/letsencrypt-plesk#132]
Let's Encrypt now has Internationalized Domain Name (IDN) Support.
https://letsencrypt.org/2016/10/21/introducing-idn-support.html

Therefore Plesk should also enable IDN Support...

**Comment by IronButterfly** [comment]
Yes, this feature is under development too. I hope we release it in Q2 2017, as support of aliases and subdomains, but maybe a bit later.

**Comment by ShamanWolffire** [comment]
Yes please make IDN Support available 👍

**Comment by j-alexander-96** [comment]
Is there any news about the support for IDN Domains?

**Comment by rkosolapov** [comment]
Let’s Encrypt 2.0.0 extension with IDN domains support is now available!

https://ext.plesk.com/packages/f6847e61-33a7-4104-8dc9-d26a0183a8dd-letsencrypt

We would love to hear your feedback on our forum at http://talk.plesk.com. We’d like to thank everyone who commented on this request and provided invaluable feedback. Thanks!
