### ISSUE TITLE
UnicodeEncodeError: Can't encode character - Ordinal not in range

### ISSUE THREAD

**Issue by shaunsmacbook** [plesk/letsencrypt-plesk#133]
No matter which domain I try, the extension always fails [after hitting the "Install" button](http://i.imgur.com/uU5MJXC.png) with the following error:

> Obtaining a new certificate
> Performing the following challenges:
> http-01 challenge for abc.com
> Waiting for verification...
> Cleaning up challenges
> 
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
> File &quot;/opt/plesk/python/2.7/lib/python2.7/atexit.py&quot;, line 24, in _run_exitfuncs
> func(*targs, **kargs)
> File &quot;/usr/local/psa/var/modules/letsencrypt/venv.kwxyQ/lib/python2.7/site-packages/certbot/reporter.py&quot;, line 74, in atexit_print_messages
> self.print_messages()
> File &quot;/usr/local/psa/var/modules/letsencrypt/venv.kwxyQ/lib/python2.7/site-packages/certbot/reporter.py&quot;, line 117, in print_messages
> next_wrapper.fill(line) for line in lines[1:]))
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xbb' in position 278: ordinal not in range(128)

[Seems like more people having the same issue](https://ext.plesk.com/packages/f6847e61-33a7-4104-8dc9-d26a0183a8dd-letsencrypt#comment-2786566701), but fixing it manually isn't the solution as it will likely get overwritten after the next update!

**Comment by IronButterfly** [comment]
`'ascii' codec can't encode character`
Looks like that somewere is non-ACSII symbol in domains settings, names, usernames, passwords, etc. You need to check it.

**Comment by xgin** [comment]
In version 2.0 we replaced Python-based certbot with PHP-based client: unicode issues should be fixed now.
