### ISSUE TITLE
SSL Install failed

### ISSUE THREAD

**Issue by Santana1053** [plesk/letsencrypt-plesk#134]
Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: Saving debug log to /opt/psa/var/modules/letsencrypt/logs/letsencrypt.log
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for mydomain.com.com
http-01 challenge for www.mydomain.com.com
Starting new HTTPS connection (1): 127.0.0.1
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. mydomain.com.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://mydomain.com.com/.well-known/acme-challenge/YPJhmXbZ45AypbIvyW2kZSZe554CfRhbsP-ikG6wM_4: &quot;&lt;html&gt;
&lt;head&gt;&lt;title&gt;403 Forbidden&lt;/title&gt;&lt;/head&gt;
&lt;body bgcolor=&quot;white&quot;&gt;
&lt;center&gt;&lt;h1&gt;403 Forbidden&lt;/h1&gt;&lt;/center&gt;
&lt;hr&gt;&lt;center&gt;&quot;, www.mydomain.com.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://www.mydomain.com.com/.well-known/acme-challenge/JKzPXjicuUkKs3dwEfuZuIJGzzLfcO5Pu3VTPNjzR8Y: &quot;&lt;html&gt;
&lt;head&gt;&lt;title&gt;403 Forbidden&lt;/title&gt;&lt;/head&gt;
&lt;body bgcolor=&quot;white&quot;&gt;
&lt;center&gt;&lt;h1&gt;403 Forbidden&lt;/h1&gt;&lt;/center&gt;
&lt;hr&gt;&lt;center&gt;&quot;
IMPORTANT NOTES:
- The following errors were reported by the server:

Domain: mydomain.com.com
Type: unauthorized
Detail: Invalid response from
http://mydomain.com.com/.well-known/acme-challenge/YPJhmXbZ45AypbIvyW2kZSZe554CfRhbsP-ikG6wM_4:
&quot;&lt;html&gt;
&lt;head&gt;&lt;title&gt;403 Forbidden&lt;/title&gt;&lt;/head&gt;
&lt;body bgcolor=&quot;white&quot;&gt;
&lt;center&gt;&lt;h1&gt;403 Forbidden&lt;/h1&gt;&lt;/center&gt;
&lt;hr&gt;&lt;center&gt;&quot;

Domain: www.mydomain.com.com
Type: unauthorized
Detail: Invalid response from
http://www.mydomain.com.com/.well-known/acme-challenge/JKzPXjicuUkKs3dwEfuZuIJGzzLfcO5Pu3VTPNjzR8Y:
&quot;&lt;html&gt;
&lt;head&gt;&lt;title&gt;403 Forbidden&lt;/title&gt;&lt;/head&gt;
&lt;body bgcolor=&quot;white&quot;&gt;
&lt;center&gt;&lt;h1&gt;403 Forbidden&lt;/h1&gt;&lt;/center&gt;
&lt;hr&gt;&lt;center&gt;&quot;

To fix these errors, please make sure that your domain name was
entered correctly and the DNS A record(s) for that domain
contain(s) the right IP address.

**Comment by IronButterfly** [comment]
Check this KB article - https://kb.plesk.com/en/129128 or this, if you have Windows - https://kb.plesk.com/en/128677
