### ISSUE TITLE
ssl spdy

### ISSUE THREAD

**Issue by Ogy** [plesk/letsencrypt-plesk#138]
Hi, i'm almost sure, it is not related to letsencrypt, anyhow, can you help me solve the 
ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY

it is displayed by google chrome in fedora 19, 20, 21
Firefox hasn't error, but displays empty website
I've check few spdy client testers, spdy works
Thanks for your time

**Comment by zolero** [comment]
Experiencing the same issue

**Comment by xgin** [comment]
The error tells about improper cipher suite for nginx.
Take a look at the documentation how to enable HTTP/2 https://docs.plesk.com/en-US/onyx/administrator-guide/web-servers/apache-web-server-linux/http2-support-in-plesk.76461/ and especially `Troubleshooting` chapter.
