### ISSUE TITLE
Failed letsencrypt execution (because of different Plesk port?)

### ISSUE THREAD

**Issue by King555** [plesk/letsencrypt-plesk#139]
When I want to obtain a certificate, I get this error message:

`Failed letsencrypt execution: Saving debug log to /opt/psa/var/modules/letsencrypt/logs/letsencrypt.log
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for example.com
http-01 challenge for www.example.com
Cleaning up challenges
An unexpected error occurred:
ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=8443): Max retries exceeded with url: /enterprise/control/agent.php (Caused by NewConnectionError('&lt;requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f81ce33f050&gt;: Failed to establish a new connection: [Errno 111] Connection refused',))
Please see the logfiles in /opt/psa/var/modules/letsencrypt/logs for more details.
IMPORTANT NOTES:
- If you lose your account credentials, you can recover through
e-mails sent to mail@example.com.
- Your account credentials have been saved in your Certbot
configuration directory at /opt/psa/var/modules/letsencrypt/etc.
You should make a secure backup of this folder now. This
configuration directory will also contain certificates and private
keys obtained by Certbot so making regular backups of this folder
is ideal. `

I see that something wants to connect to port 8443. The default Plesk ports are blocked on my server. I have set a specific IP and port combination in my Plesk config file, all other IPs and ports do not work. Maybe this is the problem here? Then the extension has to use the correct port (I don't know whether the localhost IP works then).

**Comment by xgin** [comment]
Since version 2.0 API requests are performed internally and do not depend on port.
