### ISSUE TITLE
Error: The component __perl_unix_support was not installed

### ISSUE THREAD

**Issue by dakira** [plesk/letsencrypt-plesk#14]
I was able to install a couple of certificates without problems. Suddenly I got this error.

    Error: Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: 
    2015-12-04 22:08:44,921:WARNING:letsencrypt.cli:Root (sudo) is required to run most of
    letsencrypt functionality.
    Assign certificate failure: Error: The component __perl_unix_support was not installed
    IMPORTANT NOTES:
    - Congratulations! Your certificate and chain have been saved at /opt
    /psa/var/modules/letsencrypt/etc/live/domain.net/fullchain.pem
    . Your cert will expire on 2016-03-03. To obtain a new version of
    the certificate in the future, simply run Let's Encrypt again.

So the certs seem to be generated but couldn't be installed for some reason.

**Comment by xgin** [comment]
I confirm the issue is in Plesk API, I hope it will be fixed asap.
As a workaround you can install mod_perl in Plesk Installer.

**Comment by dakira** [comment]
After installing mod_perl in the Plesk installer I could issue one certificate and for the next Domain I would get a similar error, this time for python_unix. So I went on to install mod_python using the Plesk installer and haven't had a problem since.

**Comment by dakira** [comment]
As this seems to be an error in the Plesk API and not the client I'll close this issue.
