### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by ortreum** [plesk/letsencrypt-plesk#144]
Hello,

I got this problem:

    # python setup.py install
    running install
    running bdist_egg
    running egg_info
    writing requirements to letsencrypt_plesk.egg-info/requires.txt
    writing letsencrypt_plesk.egg-info/PKG-INFO
    writing top-level names to letsencrypt_plesk.egg-info/top_level.txt
    writing dependency_links to letsencrypt_plesk.egg-info/dependency_links.txt
    writing entry points to letsencrypt_plesk.egg-info/entry_points.txt
    reading manifest file 'letsencrypt_plesk.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'LICENSE.txt'
    warning: no files found matching '*' under directory 'docs'
    writing manifest file 'letsencrypt_plesk.egg-info/SOURCES.txt'
    installing library code to build/bdist.linux-x86_64/egg
    running install_lib
    running build_py
    creating build/bdist.linux-x86_64
    creating build/bdist.linux-x86_64/egg
    creating build/bdist.linux-x86_64/egg/letsencrypt_plesk
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/__init__.py -> build/bdist.linux-x86_64/egg/letsencrypt_plesk
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/win32.py -> build/bdist.linux-x86_64/egg/letsencrypt_plesk
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/configurator.py -> build/bdist.linux-x86_64/egg/letsencrypt_plesk
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/challenge.py -> build/bdist.linux-x86_64/egg/letsencrypt_plesk
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/deployer.py -> build/bdist.linux-x86_64/egg/letsencrypt_plesk
    creating build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/__init__.py -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/challenge_test.py -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/api_mock.py -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/configurator_test.py -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/deployer_test.py -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/api_client_test.py -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests
    creating build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata
    creating build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/psa
    creating build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/psa/bin
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/psa/bin/secret_key -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/psa/bin
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/psa/version -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/psa
    creating build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_certificate_update_ok.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/request_certificate_install.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_server_get_protos_ok.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/request_server_get_protos.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_server_get_protos_legacy.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_site_get_one_error.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_certificate_remove_error.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_site_set_certificate_ok.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/request_site_set_certificate.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_site_get_one_ok.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_site_set_certificate_error.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/request_certificate_remove.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_certificate_install_error.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_certificate_update_error.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_certificate_get_pool_one.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_site_get_all_many.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/request_certificate_update.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_site_get_one_without_hosting.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_site_get_all_one.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_certificate_install_ok.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_certificate_get_pool_none.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/request_site_get_one.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_server_get_protos_error.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_site_get_all_none.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/request_site_get_all.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_certificate_get_pool_many.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/response_certificate_remove_ok.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/api/request_certificate_get_pool.xml -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/api
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/test.key -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/ca.crt -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata
    creating build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/conf
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/conf/plesk.ssl-priority.conf.txt -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/conf
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/conf/plesk.conf.txt -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/conf
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/conf/plesk.empty.conf.txt -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/conf
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/conf/plesk.ssl.conf.txt -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/conf
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/test.crt -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/full.crt -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata
    creating build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/psa8
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/tests/testdata/psa8/version -> build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/testdata/psa8
    copying build/lib.linux-x86_64-2.7/letsencrypt_plesk/api_client.py -> build/bdist.linux-x86_64/egg/letsencrypt_plesk
    byte-compiling build/bdist.linux-x86_64/egg/letsencrypt_plesk/__init__.py to __init__.pyc
    byte-compiling build/bdist.linux-x86_64/egg/letsencrypt_plesk/win32.py to win32.pyc
    byte-compiling build/bdist.linux-x86_64/egg/letsencrypt_plesk/configurator.py to configurator.pyc
    byte-compiling build/bdist.linux-x86_64/egg/letsencrypt_plesk/challenge.py to challenge.pyc
    byte-compiling build/bdist.linux-x86_64/egg/letsencrypt_plesk/deployer.py to deployer.pyc
    byte-compiling build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/__init__.py to __init__.pyc
    byte-compiling build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/challenge_test.py to challenge_test.pyc
    byte-compiling build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/api_mock.py to api_mock.pyc
    byte-compiling build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/configurator_test.py to configurator_test.pyc
    byte-compiling build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/deployer_test.py to deployer_test.pyc
    byte-compiling build/bdist.linux-x86_64/egg/letsencrypt_plesk/tests/api_client_test.py to api_client_test.pyc
    byte-compiling build/bdist.linux-x86_64/egg/letsencrypt_plesk/api_client.py to api_client.pyc
    creating build/bdist.linux-x86_64/egg/EGG-INFO
    copying letsencrypt_plesk.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying letsencrypt_plesk.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying letsencrypt_plesk.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying letsencrypt_plesk.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying letsencrypt_plesk.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying letsencrypt_plesk.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    zip_safe flag not set; analyzing archive contents...
    creating dist
    creating 'dist/letsencrypt_plesk-0.2.0.dev0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
    removing 'build/bdist.linux-x86_64/egg' (and everything under it)
    Processing letsencrypt_plesk-0.2.0.dev0-py2.7.egg
    creating /usr/local/lib/python2.7/dist-packages/letsencrypt_plesk-0.2.0.dev0-py2.7.egg
    Extracting letsencrypt_plesk-0.2.0.dev0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
    Adding letsencrypt-plesk 0.2.0.dev0 to easy-install.pth file
    
    Installed /usr/local/lib/python2.7/dist-packages/letsencrypt_plesk-0.2.0.dev0-py2.7.egg
    Processing dependencies for letsencrypt-plesk==0.2.0.dev0
    Searching for mock
    Reading https://pypi.python.org/simple/mock/
    Best match: mock 2.0.0
    Downloading https://pypi.python.org/packages/0c/53/014354fc93c591ccc4abff12c473ad565a2eb24dcd82490fae33dbf2539f/mock-2.0.0.tar.gz#md5=0febfafd14330c9dcaa40de2d82d40ad
    Processing mock-2.0.0.tar.gz
    Writing /tmp/easy_install-BKQUcs/mock-2.0.0/setup.cfg
    Running mock-2.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-BKQUcs/mock-2.0.0/egg-dist-tmp-BGrFzx
    Searching for setuptools>=17.1
    Reading https://pypi.python.org/simple/setuptools/
    Best match: setuptools 34.1.0
    Downloading https://pypi.python.org/packages/64/88/d434873ba1ce02c0ed669f574afeabaeaaeec207929a41b5c1ed947270fc/setuptools-34.1.0.zip#md5=a2f819c503b49781b1a15cfb4d49c974
    Processing setuptools-34.1.0.zip
    Writing /tmp/easy_install-BKQUcs/mock-2.0.0/temp/easy_install-CJj9Lq/setuptools-34.1.0/setup.cfg
    Running setuptools-34.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-BKQUcs/mock-2.0.0/temp/easy_install-CJj9Lq/setuptools-34.1.0/egg-dist-tmp-5gDbOt
    Traceback (most recent call last):
      File "setup.py", line 88, in <module>
        'plesk = letsencrypt_plesk.configurator:PleskConfigurator',
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 73, in run
        self.do_egg_install()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 96, in do_egg_install
        cmd.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 381, in run
        self.easy_install(spec, not self.no_deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 597, in easy_install
        return self.install_item(None, spec, tmpdir, deps, True)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 648, in install_item
        self.process_distribution(spec, dist, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 694, in process_distribution
        [requirement], self.local_index, self.easy_install
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup
        lambda: execfile(
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run
        return func()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>
        {'__file__':setup_script, '__name__':'__main__'}
      File "setup.py", line 6, in <module>
        from setuptools import setup
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup
        lambda: execfile(
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run
        return func()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>
        {'__file__':setup_script, '__name__':'__main__'}
      File "setup.py", line 191, in <module>
    
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)

    [76 times begin ]

      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 276, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2100, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer)))
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 292, in fetch_build_egg
        dist = self.__class__({'script_args':['easy_install']})
    
    [76 times end ]
    
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 276, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2100, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer)))
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 613, in resolve
        env = Environment(self.entries)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 782, in __init__
        self.scan(search_path)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 811, in scan
        for dist in find_distributions(item):
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1826, in find_on_path
        path_item,entry,metadata,precedence=DEVELOP_DIST
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2206, in from_location
        py_version=py_version, platform=platform, **kw
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2183, in __init__
        self.project_name = safe_name(project_name or 'Unknown')
    RuntimeError: maximum recursion depth exceeded

Michael

**Comment by xgin** [comment]
You're eating it wrong.
Just install the extension in Plesk: https://ext.plesk.com/packages/f6847e61-33a7-4104-8dc9-d26a0183a8dd-letsencrypt
We are not going to continue support the python plugin because we have reliable (as we believe) implementation in PHP.
