### ISSUE TITLE
Problem with CLI and subdomain registration

### ISSUE THREAD

**Issue by jkfran** [plesk/letsencrypt-plesk#148]
Hello I want to get a certificate for sub.domain.com, I run:

`plesk bin extension --exec letsencrypt cli.php --domain sub.domain.com --agree-tos --email foo@bar.com`

But I get this error:

```
 - The following errors were reported by the server:

   Domain: sub.domain.com
   Type:   connection
   Detail: Could not connect to www.sub.domain.com
```
Why www.sub.domain.com? I just want sub.domain.com

I try with -d and --domain but same result.

**Comment by xgin** [comment]
Has the subdomain been used with `www` prefix before?
The previous configuration is likely saved in `/usr/local/psa/var/modules/letsencrypt/etc/renewal/sub.domain.com.conf` - try to remove this file.

**Comment by jkfran** [comment]
@xgin I don't have this configuration file :(

**Comment by jkfran** [comment]
Ok, it was a problem with the Plesk subscription.

I forgot to create the subscription with:
`plesk bin subscription -c ... -www false -seo-redirect non-www`

Thank you anyway.
