### ISSUE TITLE
Bulk function for every domain

### ISSUE THREAD

**Issue by maltris** [plesk/letsencrypt-plesk#15]
Is it possible to bulk-letsencryptify all domains on the extensions list? With a big number of domains it doesn't seem to make sense to order a certificate one-by-one.

Thanks in advance!

**Comment by maltris** [comment]
Since there was no answer, but a suggestion about using the cli for generating certificates, I quickly used this one-liner:

```
for i in `mysql -uadmin -p\`cat /etc/psa/.psa.shadow\` psa -Ns -e "select name from domains"`; do sudo -u psaadm bash /usr/local/psa/admin/plib/modules/letsencrypt/scripts/le-run -d "$i" -d www."$i"; done
```

Source: https://github.com/plesk/letsencrypt-plesk/issues/4#issuecomment-162272534

**Comment by xgin** [comment]
Take a look at the Security Advisor extension:
https://ext.plesk.com/packages/6bcc01cf-d7bb-4e6a-9db8-dd1826dcad8f-security-advisor
Bulk operation is now supported!
