### ISSUE TITLE
__future__ import print_function in plesk extension 1.9.3 not supported?

### ISSUE THREAD

**Issue by funkoolow** [plesk/letsencrypt-plesk#155]
hello, on my plesk 12.5.30 runnin on centos-release-6-8.el6.centos.12.3.x86_64, trying to issue a certificate on a domain via the let's encrypt extension, now refers the following:

```
Errore: Installazione del certificato SSL
Let's Encrypt non riuscita: Failed letsencrypt execution: Could not find
platform dependent libraries <exec_prefix>

Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
File "/usr/local/psa/var/modules/letsencrypt/venv/bin/certbot", line 7, in <module>
from certbot.main import main
File
"/usr/local/psa/var/modules/letsencrypt/venv.LrOn7/lib/python2.7/site-packages/certbot/main.py",
line 2, in <module>
from __future__ import print_function
```

ImportError: No module named __future__

Already tried
this solution -> http://unix.stackexchange.com/questions/303702/cant-start-gns3-due-to-python-issues/303748
and this solution -> https://talk.plesk.com/threads/letss-encrypt-issue.340537/
without any luck

The extension was originally installed via plesk extension installer, since I want to avoid any extra mess installing from external repos or sources to maximize stability.

If I understand correctly, the plesk extension includes a python2.7 copy, is it possible that this pack lacks the support for the required module it refers to?

thanks anyone for any possible help

**Comment by xgin** [comment]
In version 2.0 we replaced Python-based certbot with PHP-based client: neither python nor external repos are used now.
