### ISSUE TITLE
Domainaliases which are (Sub-)domains without www. prefix won't work with version 2.0.0

### ISSUE THREAD

**Issue by BastianBalthasarBux** [plesk/letsencrypt-plesk#157]
There is a problem with adding Domain-Aliases which are not using the www subdomain e.g. extranet.acme.com.
Let's encrypt then tries to resolve www.extranet.acme.com which leads to an error if that subdomain does not resolve to the same server and vhost.
ATM I can't see a way via GUI to prevent the www. subdomain being used for domain-aliases, at least if the main domain has it enabled.

**Comment by lucjager** [comment]
I think they need to update the plugin, having issues here too.

e.g.

Error: Let's Encrypt SSL certificate installation failed: Invalid response from https://acme-v01.api.letsencrypt.org/acme/new-authz: Must agree to subscriber agreement before any further actions.
Type: urn:acme:error:unauthorized.

**Comment by rkosolapov** [comment]
Could you please check the issue on 2.0.2 version of LE Extension?  It should be fixed now.

**Comment by BastianBalthasarBux** [comment]
Nope, does not work:
Warnung: Failed to resolve challenge for www.subdomain.xxx.com. Details:
Challenge marked as invalid. Details: Invalid response from http://www.subdomain.xxx.com/.well-known/acme-challenge/

where www.subdomain.xxx.com is not a subdomain which resolves anyway. only "subdomain.xxx.com" resolves.
subdomain.xxx.com is an alias for domainyyy.com (which has activated to add www.domainyyy.com too)

**Comment by BastianBalthasarBux** [comment]
can you reopen that issue?

**Comment by rkosolapov** [comment]
Could you set log.filter.priority=7 in panel.ini, reproduce the issue and provide us with the panel.log records?

**Comment by BastianBalthasarBux** [comment]
ahm, ok, the subdomain with the www. prefix resolves.
but to a completely different server, serving some custom error-page. and i do not have access to their dns as it is a 'foreign' domain.
edge-case i would like to say ...

So, if I check 'add www.maindomain.com', and i have several subdomains, where the www. prefix is NOT resolving at all, i get some fat warning boxes in yellow, but the subdomain-certificates without the www. prefix are at least issued and added. Thanks for that!

**Comment by BastianBalthasarBux** [comment]
sorry for that 'edge-case' i help myself on this with adding a domain to the same directory of the webserver. not nice, but until the customer does not get the dns-records clean, i can live with that ... ;)
so from my side: you can keep this issue as closed.

Well done, many thanks!
