### ISSUE TITLE
Domain Alias option not available in Plesk Onyx with Let's Encrypt 2.0.0-21

### ISSUE THREAD

**Issue by amavarick** [plesk/letsencrypt-plesk#158]
I updated the extension to Let's Encrypt 2.0.0-21 and Plesk Onyx Version 17.0.17 Update #21 and do not see any options to add aliases as shown in the Plesk Extension Catalog for Let's Encrypt. I tried renewing existing domain and also deleting Let's Encrypt SSL and replacing with self-signed and then re-installing Let's Encrypt SSL and still no alias options. I even uninstalled Let's Encrypt extension and re-installed. No joy. How do I get this option?

**Comment by redhell** [comment]
Are you sure that you have an Domain alias? It won't work for subdomains.

**Comment by xgin** [comment]
Domain aliases should have the web service enabled (with the green icon on the overview).
Take a look at the discussion with screenshots here: https://ext.plesk.com/packages/f6847e61-33a7-4104-8dc9-d26a0183a8dd-letsencrypt#comment-3227231448
