### ISSUE TITLE
Support for htaccess secured domains

### ISSUE THREAD

**Issue by Novaal** [plesk/letsencrypt-plesk#16]
Hello,

the process fails when trying to install or to renew a certificate on  a domain which needs authorization (.htaccess username - password).

>Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: 2015-12-05 12:13:32,772:WARNING:letsencrypt.cli:Root (sudo) is required to run most of letsencrypt functionality.
>Failed authorization procedure. example.tld (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://example.tld/.well-known/acme-challenge/....[xxx.xxx.xxx.xxx]: 401
>IMPORTANT NOTES:
>- The following 'urn:acme:error:unauthorized' errors were reported by
>the server:
>
>Domains: example.tld
>Error: The client lacks sufficient authorization

I would suggest, that the extension can add a rule in htacces-file, so that the token under "example.tld/.well-known/acme-challenge/...." can be read automatically. After installation/renewal, the rule could be removed autmatically.

**Comment by djimno** [comment]
I think, this is the same thread in #13

**Comment by xgin** [comment]
@Novaal see https://github.com/plesk/letsencrypt-plesk/issues/13#issuecomment-162913186
