### ISSUE TITLE
Broken devblog link in README

### ISSUE THREAD

**Issue by bmw** [plesk/letsencrypt-plesk#163]
Certbot dev here. Some of our tests on our website broke because [we've been linking](https://certbot.eff.org/#debianjessie-plesk) people to https://devblog.plesk.com/2015/12/lets-encrypt-plesk/ which is linked the README of this repo, but now returns a 404.

Is there somewhere else people should be linked instead? Maybe https://ext.plesk.com/packages/f6847e61-33a7-4104-8dc9-d26a0183a8dd-letsencrypt?

**Comment by xgin** [comment]
Hi! The blog links are changeable as you have noticed.. The actual information is maintained at the extension overview page: https://ext.plesk.com/packages/f6847e61-33a7-4104-8dc9-d26a0183a8dd-letsencrypt
Thank you for pointing it out! I've updated the readme and created the PR https://github.com/certbot/website/pull/206
