### ISSUE TITLE
InvalidEmail when using cli.php script

### ISSUE THREAD

**Issue by slue** [plesk/letsencrypt-plesk#164]
When using the cli version of the extension, I get the following results:

```
plesk bin extension --exec letsencrypt cli.php -d mydomain.com
Executing /opt/psa/admin/plib/modules/letsencrypt/scripts/cli.php failed: Invalid response from https://acme-v01.api.letsencrypt.org/acme/new-reg: Error creating new registration.
Type: urn:acme:error:invalidEmail.

exit status 1
```

When doing it in the administration view of plesk, it works.

I do not know if this is right here, as I cannot find any cli.php script in this repo.
Maybe you could guide me to the right direction?

thanks, Christoph

**Comment by UFHH01** [comment]
**Hi slue,**

you should ALWAYS include the option string "**--email YOUR-EMAIL-ADRESS@YOUR-DOMAIN.COM**" , because you HAVE TO use a registered eMail - address in each command, where validation from Let's Encrypt is involved. ;-)

**Comment by slue** [comment]
HI @UFHH01 

thanks a lot. Can you tell me where I could have gotten this Information by myself? Is there any kind of documentation?

thanks, Christoph
