### ISSUE TITLE
Renew Issue

### ISSUE THREAD

**Issue by Lucaber** [plesk/letsencrypt-plesk#167]
Im trying to renew a Let´s Encrypt Certificate on my Plesk Server
Im getting no real error message, only:
"Error: Let's Encrypt SSL certificate installation failed: Install certificate failure: Unable to set certificate name : "

After a few tries I am getting:
"Error: Let's Encrypt SSL certificate installation failed: Invalid response from https://acme-v01.api.letsencrypt.org/acme/new-cert1: Error creating new cert :: too many certificates already issued for exact set of domains: gitlab.micronited.de,www.gitlab.micronited.de. Type: urn:acme:error:rateLimited."
Because Let´s Encrypt blocks a domain after 10 certificates a week.

I also noticed that Plesk tries to renew the certificate of my other domain every day
https://crt.sh/?q=micronited.de

**Comment by UFHH01** [comment]
**Hi Lucaber,**

pls. see the provided suggestions from the WIKI - article:

[https://github.com/plesk/letsencrypt-plesk/wiki/Error-%22Unable-to-set-certificate-name-:%22](https://github.com/plesk/letsencrypt-plesk/wiki/Error-%22Unable-to-set-certificate-name-:%22)
