### ISSUE TITLE
Install certificate failure: Unable to set certificate name : 

### ISSUE THREAD

**Issue by Happyfeet01** [plesk/letsencrypt-plesk#168]
Hello, 

i have Issue when i try to renew an certificate

`Fehler: Fehler bei der Installation des SSL-Zertifikats von Let's Encrypt: Install certificate failure: Unable to set certificate name : `
 i read here https://github.com/plesk/letsencrypt-plesk/issues/7 that is an Plesk API Issue. Maybe again?

My System:

- ubuntu 16.04

-  Plesk Onyx Version 17.5.3 Update #5

- Letsencrypt Version 2.0.3-31

i see also there are only 2 subdomains in this Folder:
  /opt/psa/var/modules/letsencrypt/live

**Comment by UFHH01** [comment]
**Hi Happyfeet01,**

pls. see the provided suggestions from the WIKI - article:

[https://github.com/plesk/letsencrypt-plesk/wiki/Error-%22Unable-to-set-certificate-name-:%22](https://github.com/plesk/letsencrypt-plesk/wiki/Error-%22Unable-to-set-certificate-name-:%22)

**Comment by xgin** [comment]
Fixed in the extension version 2.1.0
