### ISSUE TITLE
Saving the previously used e-mail adress

### ISSUE THREAD

**Issue by Novaal** [plesk/letsencrypt-plesk#17]
Hi,
At the moment, wehn renewing the Cert manually, the previously used E-mail is overwritten by the profile mail address.
I suggest, that the previously used E-Mail Address is saved.

I don't know what happens when the Cert is renewed automatically, but i hope, that the previously used mail address is used again.

**Comment by xgin** [comment]
The issue is fixed in the extension version 1.1
You should upgrade the extension and create a certificate again - the email should be saved.
