### ISSUE TITLE
Error: Let's Encrypt SSL certificate installation failed: Could not obtain directory

### ISSUE THREAD

**Issue by KnightAR** [plesk/letsencrypt-plesk#170]
I get this error trying to create a SSL Cert on a subdomain, everything was working fine until I updated to 2.1.0 today.

> Error: Let's Encrypt SSL certificate installation failed: Could not obtain directory: Invalid response: &lt;HTML&gt;&lt;HEAD&gt;&lt;TITLE&gt;Error&lt;/TITLE&gt;&lt;/HEAD&gt;&lt;BODY&gt;
> An error occurred while processing your request.&lt;p&gt;
> Reference&amp;#32;&amp;#35;97&amp;#46;b50af748&amp;#46;1495178891&amp;#46;2904224
> &lt;/BODY&gt;&lt;/HTML&gt;
> .
> Status: 504.

**Comment by TeaserTrailer** [comment]
I get the same message when I try to renew my certicates :(

Please help!

**Comment by xgin** [comment]
The error seems on the Let's Encrypt CA side.
According to https://letsencrypt.status.io/ there was an incident.
Try again a bit later.

**Comment by TeaserTrailer** [comment]
Doh! didn't think about checking that one!

Thanks xgin! :)

**Comment by micfrip** [comment]
Same issue from my side with a Prestashop website

**Comment by TomRZaperoo** [comment]
Same issue here, windows 2012 server R2. Checked the status page here: https://letsencrypt.status.io/ but this error is still happening:

Error: Let's Encrypt SSL certificate installation failed: Could not obtain directory: Invalid response: &lt;HTML&gt;&lt;HEAD&gt;&lt;TITLE&gt;Error&lt;/TITLE&gt;&lt;/HEAD&gt;&lt;BODY&gt;
An error occurred while processing your request.&lt;p&gt;
Reference&amp;#32;&amp;#35;97&amp;#46;5df01202&amp;#46;1495207546&amp;#46;2b7cca6f
&lt;/BODY&gt;&lt;/HTML&gt;
.
Status: 504.

**Comment by Vsnumimmy** [comment]
Error: Let's Encrypt SSL certificate installation failed: Challenge marked as invalid. Details: Invalid response from http://domain.com/.well-known/acme-challenge/-kvBKJDlPfo6-ZI6ZneDTwrgbYvmCHGW-Tai4hZSZEw: &quot;&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
&lt;html xmlns=&quot;http&quot;

How to fix this error ?

**Comment by xgin** [comment]
The service is operational now (since May 19, 2017 11:05PM UTC).

@Vsnumimmy the error you got (unfortunately the output is incomplete) seems an issue of your website, e.g. rewrite rules, special nginx locations and other customization of your application.  Try to search on the [forum](https://talk.plesk.com/), I think are many similar cases and walkthroughs. However it does not related to the current issue.
