### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by mat-l** [plesk/letsencrypt-plesk#171]
Hello,
the installation of new certificates is failing with the following error:
Fehler: Fehler bei der Installation des SSL-Zertifikats von Let's Encrypt: Challenge marked as invalid. Details: Invalid response from http://ad-quadrat.de/.well-known/acme-challenge/7Va3uzLCOw61AU8_XriMPYP-1m6MYFbX4qoPsnTF8fY: &quot;&lt;HTML&gt;
&lt;HEAD&gt;
&lt;TITLE&gt;404 Not Found&lt;/TITLE&gt;
&lt;BASE href=&quot;/error_docs/&quot;&gt;&lt;!--[if lte IE 6]&gt;&lt;/BASE&gt;&lt;![endif]--&gt;
&lt;/HEAD&gt;
&lt;BODY&gt;
&lt;H1&gt;No&quot;

Running plesk-letsencrypt on:
Betriebssystem:	‪CentOS Linux 7.3.1611 (Core)‬
Produkt	: Plesk Onyx 
Version 17.5.3 Update #6

**Comment by xgin** [comment]
Useful comment: https://ext.plesk.com/packages/f6847e61-33a7-4104-8dc9-d26a0183a8dd-letsencrypt#comment-3312235348

> If the acme-challenge fails (wrong response or 404 Not Found), make sure you don't have an ipv6 DNS AAAAA record pointing elsewhere. It seems that Letsencrypt will try an ipv6 record before the ipv4.
> So, correct the ipv6 to the one attached to your server, or delete the DNS record.
> Worked for me!

**Comment by mat-l** [comment]
The IPv6 address showed to the wrong website, therefore letsencrypt couldn't load the certificate. Thank you very much, now it is working again!
