### ISSUE TITLE
Auto renewals not working

### ISSUE THREAD

**Issue by tonytones09** [plesk/letsencrypt-plesk#174]
Auto renewals appear to not be updating the certificates in IIS.  From a support forum on Plesk, we found a work around (cause due to the SSL securing Plesk being one of another domain - CA of Let's Encrypt) by running the following as a schedule task:

Batch File:
--------------------------------------------------
@echo off
"%plesk_cli%\\repair" --reconfigure-ssl-certificates
Powershell.exe -ExecutionPolicy Bypass -File <Location of Powershell Script>\SSLFix.ps1
--------------------------------------------------
Powershell Script:
--------------------------------------------------
$Plesk_admin_password = "<PASSWORD>"
$file = 'C:\temp.txt'
$app = '"$env:plesk_cli\repair.exe"'
$option = '--reconfigure-web-site -web-site-name'
$mysql = '"$env:plesk_dir\MySQL\bin\mysql.exe"'
$mysql_options = '-uadmin -p"$Plesk_admin_password" -P8306 -e'
$mysql_query = 'select name from domains where status = 0 and cert_rep_id != 0'
$mysql_end = 'psa | Out-File $file'
Invoke-Expression "& $mysql  $mysql_options '$mysql_query' $mysql_end"
(Get-Content $file | Select-Object -Skip 1) | Set-Content $file
$a = Get-Content $file

ForEach ($dom in $a)
{
   Invoke-Expression "& $app $option $dom"
}
Remove-Item $file
--------------------------------------------------

**Comment by AdamB7586** [comment]
If you are still experiencing issue I would make sure that you have the latest version of Let's Encrypt installed. Im the one who originally made the post on the forum but this bug was fixed with the release of version 2.0.0 in March.
