### ISSUE TITLE
Subdomain support

### ISSUE THREAD

**Issue by torstenfeld** [plesk/letsencrypt-plesk#18]
Let's say, the domain in Plesk is domain.com, will there be an option to have the certificate include subdomains like www.domain.com? 

Are you aware of a workaround to create a certificate for www.domain.com through this plugin?

**Comment by COhsrt** [comment]
I guess you are talking about SAN Support - I should have read this earlier before opening #19
Anyway, I guess this is the same need!

**Comment by mrclschstr** [comment]
See #4.

**Comment by Novaal** [comment]
Supporting multiple Subdomains in one Certificate would be a solution for the Error "Too many certificates already issued for...". Subdomains seems to get counted to the top-level Domain.
https://community.letsencrypt.org/t/public-beta-rate-limits/4772/2

**Comment by xgin** [comment]
Close as duplicate
