### ISSUE TITLE
Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: 

### ISSUE THREAD

**Issue by eladnova** [plesk/letsencrypt-plesk#21]
I notice the SSL Cert install fails on occasion and I typically get the following error.

>Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution (etc...)

Here's a use case.
VPS 02 hosts domain.com and the site is live with the DNS pointing at it.

I copy the site to VPS 02 for testing and am using the PLESK preview URL. 
The DNS is not switched over because I am testing.
Is there any way to get around this? The full error is below.

Apart from the Python error which I think is separate, there is an error about not finding
".well-known/acme-challenge" etc on the domain.

> Error: Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: /usr/local/psa/var/modules/letsencrypt/venv.FVUDD/lib/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the > > Python core team, please upgrade your Python.
> DeprecationWarning
> 2015-12-06 15:56:31,977:WARNING:letsencrypt.cli:Root (sudo) is required to run most of letsencrypt functionality.
> /usr/local/psa/var/modules/letsencrypt/venv.FVUDD/lib/python2.6/site-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
> InsecureRequestWarning)
> Failed authorization procedure. edenstudios.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://domain.com/.well-known/acme-challenge/-l2tp0lISSfUh-zbQjSZa6sw6_l02WEnSmN8in6JD0o [XXX.78.0.XXX]: 403
> IMPORTANT NOTES:
> - The following 'urn:acme:error:unauthorized' errors were reported by
the server:

> Domains: domain.com
> Error: The client lacks sufficient authorization

**Comment by djimno** [comment]
See #13

**Comment by xgin** [comment]
As far as I have understood, the domain is not resolved to VPS 02 and cannot be reached globally.
That means there is no ability to proof the ownership of the domain.
Try to perform authentication manually https://letsencrypt.readthedocs.org/en/latest/using.html#manual
