### ISSUE TITLE
Installation fails on post-install.php with an Permission denied error

### ISSUE THREAD

**Issue by MarcoBienlein** [plesk/letsencrypt-plesk#22]
When I try to install the Let's Encrypt on my Plesk 12.5.30 on Ubuntu 12.04.1 LTS‬ I get the following error:

Executing /opt/psa/admin/plib/modules/letsencrypt/scripts/post-install.php failed: sh: 1: /opt/psa/admin/bin/modules/letsencrypt/le-installer: Permission denied

What to do to correct the permission issues?

**Comment by xgin** [comment]
@MarcoBienlein Did you try to reinstall the extension?
Try to run `sudo -u psaadm /opt/psa/admin/bin/modules/letsencrypt/le-installer`
If it does not work run `sudo /opt/psa/admin/sbin/modules/letsencrypt/le-installer`
Show me permissions of these files.

**Comment by MarcoBienlein** [comment]
Fist, reinstalled current release (1.2.1) - same issue on the web interface...
Second, tried to execute le-installer script as root on a ssh session - le-installer at /opt/psa/admin/bin/modules/letsencrypt/le-installer seems to be an invalid symbolic link to ../../../sbin/mod_wrapper.
Then executed le-installer script at /opt/psa/admin/sbin/modules/letsencrypt/le-installer. Although there were some warnings, the extension seems to work!

Thank you very much!!!

The messages when running the le-installer script again (including the warnings on first call):
Bootstrapping dependencies for ubuntu precise...
Creating virtual environment...
The --no-site-packages flag is deprecated; it is now the default behavior.
Updating letsencrypt and virtual environment dependencies...
/usr/local/psa/var/modules/letsencrypt/venv.oSHT1/local/lib/python2.7/site-packages/pip/pep425tags.py:66: RuntimeWarning: invalid Python installation: unable to open /usr/psa/var/modules/letsencrypt/venv.oSHT1/lib/python2.7/config/Makefile (No such file or directory)
  warnings.warn("{0}".format(e), RuntimeWarning)
/usr/local/psa/var/modules/letsencrypt/venv.oSHT1/local/lib/python2.7/site-packages/pip/pep425tags.py:66: RuntimeWarning: invalid Python installation: unable to open /usr/psa/var/modules/letsencrypt/venv.oSHT1/lib/python2.7/config/Makefile (No such file or directory)
  warnings.warn("{0}".format(e), RuntimeWarning)
Switch venv to the installed one...
Done

**Comment by xgin** [comment]
> le-installer at /opt/psa/admin/bin/modules/letsencrypt/le-installer seems to be an invalid symbolic link to ../../../sbin/mod_wrapper
That is bad, you might encounter problems with different extensions that require 'sbin' scripts.
Does /opt/psa/admin/sbin/mod_wrapper exist?
Maybe you have removed it accidentally?

**Comment by MarcoBienlein** [comment]
> Maybe you have removed it accidentally?
I've added and removed the le plugin three or four times, but added or removed no other plugin (manually).
> Does /opt/psa/admin/sbin/mod_wrapper exist?
Yes, this are the permissions:
-r-s--x---  1 root root    18K Aug 26 15:26 mod_wrapper

**Comment by xgin** [comment]
The permissions are wrong:
```
# ls -la /opt/psa/admin/sbin/mod_wrapper
---s--x--- 1 root psaadm 23040 Jan 15 04:51 /opt/psa/admin/sbin/mod_wrapper
```
Your installation might have been incomplete, run `plesk repair installation` or change permissions manually:
```
# chown root:psaadm /opt/psa/admin/sbin/mod_wrapper
# chmod 4110 /opt/psa/admin/sbin/mod_wrapper
```
