### ISSUE TITLE
Created certificates are not valid

### ISSUE THREAD

**Issue by mentor2k1** [plesk/letsencrypt-plesk#23]
Hi,

some weeks ago, i created the certificates for 3 domains without the plugin on the server, including the www and non-www version of the domain.

1 of this domains is a non-www variant the other 2 will be redirected to the www variant.

These behavior is configured in the hosting settings of the domains as prefered domain (www/non-www)

I have no problems with the non-www domain, as the plugin created certificate is up and running.

But: all www-domain generated certificates are unsafe with an 

NET::ERR_CERT_COMMON_NAME_INVALID error in Chrome.

any ideas or hint´s, how i can solve this problem?

// Oliver

**Comment by MatrixCrawler** [comment]
I think this might relate to #4 

You'll find a workaround there

**Comment by mentor2k1** [comment]
Thanks @MatrixCrawler

indeed you are right. Search the issues before posting, but didn´t find it, sry.

As my old certificates also exists and valid until Feb/2016, i will wait for the next version.
