### ISSUE TITLE
SSL Error on certificate generation

### ISSUE THREAD

**Issue by ncioj10** [plesk/letsencrypt-plesk#24]
Hi,
when I want to generate a certificate for a sub domain in Plesk I receive the error below. It appears directly after entering the email address and submitting it. 
I've updated Plesk and tried to reinstall the plugin, but both had no effect.

Yours Sincerely Nicolas

 Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: Traceback (most recent call last):
File &quot;/opt/psa/var/modules/letsencrypt//venv/bin/letsencrypt&quot;, line 7, in &lt;module&gt;
from letsencrypt.cli import main
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.rqH6l/local/lib/python2.7/site-packages/letsencrypt/cli.py&quot;, line 17, in &lt;module&gt;
import OpenSSL
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.rqH6l/local/lib/python2.7/site-packages/OpenSSL/__init__.py&quot;, line 8, in &lt;module&gt;
from OpenSSL import rand, crypto, SSL
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.rqH6l/local/lib/python2.7/site-packages/OpenSSL/rand.py&quot;, line 11, in &lt;module&gt;
from OpenSSL._util import (
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.rqH6l/local/lib/python2.7/site-packages/OpenSSL/_util.py&quot;, line 6, in &lt;module&gt;
from cryptography.hazmat.bindings.openssl.binding import Binding
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.rqH6l/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py&quot;, line 13, in &lt;module&gt;
from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: libffi.so.5: cannot open shared object file: No such file or directory

**Comment by ncioj10** [comment]
Found the solution!
Fixed it with: sudo apt-get install --reinstall libffi5

**Comment by xgin** [comment]
@ncioj10 could you specify your OS? may be we have some missing dependencies.

Did anybody else face the error?

**Comment by ncioj10** [comment]
This error Occured on a Debian OS 7.(9) machine with all updates installed and a the newest version of Plesk installed aswell.

**Comment by Ack2Toni** [comment]
@xgin Got the same error on Debian Jessie.
Symlinking didn't worked for me for libffi.so.5

**Comment by xgin** [comment]
@Ack2Toni Does `sudo apt-get install --reinstall libffi5` solve it?
We really have missing dependency on that package. But on most systems it is already installed. It will be fixed soon.

**Comment by Ack2Toni** [comment]
@xgin Debian 8 got me libffi6

`dpkg -S libffi.so` gave me:
libffi6:amd64: /usr/lib/x86_64-linux-gnu/libffi.so.6.0.2
libffi6:amd64: /usr/lib/x86_64-linux-gnu/libffi.so.6
libffi-dev:amd64: /usr/lib/x86_64-linux-gnu/libffi.so

Symlinking /usr/lib/x86_64-linux-gnu/libffi.so.6  to  /usr/lib/x86_64-linux-gnu/libffi.so.5 gave me the following error:
ImportError: No module named _ssl

**Comment by xgin** [comment]
@Ack2Toni oh, you had performed dist-upgrade. you should reinstall the extension (download from catalog and upload to Plesk again) - it should use Jessie repos now.
We will try to handle it in post-dist-upgrade scripts.

**Comment by Ack2Toni** [comment]
@xgin WOW that did the trick!
shizzle is working again thanks!

**Comment by xgin** [comment]
We have updated system packages: now it requires `libffi5` for deb6 and deb7, `libffi6` for deb8 and ubuntu, `libffi` for centos and rhel

**Comment by rudybroersma** [comment]
I faced this issue after a dist-upgrade. Reinstalled solved the issue. Plesk / Odin officially supports dist-upgrade from Wheezy to Jessie, so I believe this should be considered a bug.
