### ISSUE TITLE
Version for Windows

### ISSUE THREAD

**Issue by AlfonsoML** [plesk/letsencrypt-plesk#25]
Would it be possible to add support for Windows using a library like [ACMESharp](https://github.com/ebekker/ACMESharp)?

**Comment by xgin** [comment]
Note: SNI is supported in Windows 2012 and later.

**Comment by xgin** [comment]
Windows support has been released in the extension version 1.5-1
Supported OS is Windows 2012 and later
Plesk 12.5 MU#24 is required
