### ISSUE TITLE
your connection to is encrypted using an obsolete cipher suite

### ISSUE THREAD

**Issue by TeHashX** [plesk/letsencrypt-plesk#26]
Like title say, in chrome browser

**Comment by sugdyzhekov** [comment]
Restart your browser.

**Comment by TeHashX** [comment]
![cipher](https://cloud.githubusercontent.com/assets/1405188/11654386/e14029e6-9dad-11e5-8aeb-f8d03b03c6bd.png)

Not a solution :(

**Comment by DavidAkroyd** [comment]
This is not a problem with Let's Encrypt - this is a problem with the cipher suites which your web server is serving. You will need to edit your web server configuration to only support strong ciphers.
To solve, please look at:
https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
and
https://weakdh.org/sysadmin.html

**Comment by xgin** [comment]
I hope this should help: http://docs.plesk.com/en-US/12.5/advanced-administration-guide-linux/pci-dss-compliance/tune-plesk-to-meet-pci-dss-on-linux.65871/

**Comment by DavidAkroyd** [comment]
Thanks Xgin - I didn't realise that there was a setting to set it globally, rather than per domain!

**Comment by TeHashX** [comment]
:+1:  Thanks, I just run
````
plesk sbin pci_compliance_resolver --enable
````
And now connection is encrypted using a modern cipher suite
