### ISSUE TITLE
Additional User Account error: Permission denied

### ISSUE THREAD

**Issue by wpnzach** [plesk/letsencrypt-plesk#27]
Only the "admin" username in my Plesk install is allowing certs to be added.  I have another administrator account with all the same permissions as the "admin" account, and "Error: Permission denied." is displayed when trying to open the LetsEncrypt extension under that user, even for webspaces which they have created.

**Comment by xgin** [comment]
@wpnzach if you want to have an additional admin login, you'd better create it in Tools&Settings >  Additional Administrator Accounts.
Because users, you're talking about, are restricted to use Plesk API.

**Comment by xgin** [comment]
By a lucky chance the issue has been fixed in Plesk Onyx.
