### ISSUE TITLE
Support for domain aliases

### ISSUE THREAD

**Issue by OrangeFoil** [plesk/letsencrypt-plesk#28]
For a website with multiple second level domains it should be possible to also add any domain aliases to the certificate.
Right now certificates can be generated for domain.tld and optionally www.domain.tld. If there is a another domain like alias.tld configured as an alias in Plesk it would be great to have an option to also include alias.tld and www.alias.tld as alternative domain names.

**Comment by JHGitty** [comment]
+1 :+1:

**Comment by mrclschstr** [comment]
See #19

**Comment by Natim** [comment]
Doesn't this works in that case?

    ./letsencrypt-auto certonly --webroot -w /var/www/example -d example.com -d www.example.com -w /var/www/thing -d thing.is -d m.thing.is

**Comment by xgin** [comment]
As a workaround the certificated could be issued with --webroot and then installed in Plesk (with the plugin or in UI).
But the renewal task will unfortunately loose it.

**Comment by Rar9** [comment]
Is there any solution in sight??  Or a way to  setup a config  file  that links all domain  aliases so the scheduled task will  renew them automatically ?

**Comment by mfehmer** [comment]
I tried to get it work by this way, but I couldn't get it to work..
```
./letsencrypt --renew-by-default --no-redirect --agree-tos --text --config-dir /opt/psa/var/modules/letsencrypt//etc --work-dir /opt/psa/var/modules/letsencrypt//lib --logs-dir /opt/psa/var/modules/letsencrypt//logs --authenticator letsencrypt-plesk:plesk --installer letsencrypt-plesk:plesk --email mail@server.tld -d domain.tld -d www.domain.tld -d alias.tld -d www.alias.tld
```

The auto method also does not work, because of some dns errors, I cannot fix.

Do you know, when the update with aliases will be ready?

**Comment by jeremiepape** [comment]
+1 for aliases, a lot of people need to add certif on aliases for multilingual websites based on the main site.
www.website.com
   www.website.fr
   www.website.de ....

**Comment by AlphawolfWMP** [comment]
:+1:

**Comment by AmaZili** [comment]
+1 people need to add certif on aliases for multilingual websites

**Comment by wblondel** [comment]
+1 I'm facing the same issue

**Comment by Rar9** [comment]
+1 alias domain Certifacte still not working :-(

**Comment by elanghout** [comment]
+1 for adding aliasses (multisite/multidomain drupal websites) as alternative names to the main certificate.

**Comment by mschroettle** [comment]
+1 for adding aliasses (multisite/multidomain wordpress websites) as alternative names to the main certificate.

**Comment by xylo** [comment]
+1

**Comment by futureweb** [comment]
:+1:

**Comment by FabianNiesen** [comment]
+1 I really need this feature!

**Comment by mickert** [comment]
+1   I also need this badly and I suspect everyone needs this, even if they don’t realise it yet. ;)
Most site owners have different second level domains and hyphenated domain aliases for the same site. It would be good security practice if the correct certificate (with the right Subject Alternative Names) was returned on requests to those domain aliases.
This is a “Must Have”, not a Should, Could or Would have.

**Comment by jtherin** [comment]
+1 to solve "SSL_ERROR_BAD_CERT_DOMAIN" on aliases.

**Comment by Sennik** [comment]
+1 Really need this!

**Comment by StoneISStephan** [comment]
A possible solution would be to create all these domains (Subject Alt Names) as sites in Plesk.

Then run:

echo 'user@domain.com' | sudo -u psaadm bash /usr/local/psa/admin/plib/modules/letsencrypt/scripts/le-run -d site1.com -d site2.com -d site3.com

The extension will then query the API for the doc root of these sites and drop the .well-known directory + verification files.


Afterwards you will get a certificate with the correct Subject Alt Names.
And you can delete all additional sites and recreate them as aliases without 301 redirect.


This however does not solve the renewal process.


For this, the Extension should have some logic to check that if a site does not exist for the domain, it doesn't happen to be an alias for some domain.
If it is an alias, it should request the docroot of the main site and drop the .well-known there.
This will fix auto renewals aswell.

**Comment by rumpus** [comment]
+1 for domain alias support

**Comment by krisc78** [comment]
+1 to solve "SSL_ERROR_BAD_CERT_DOMAIN" on aliases.

**Comment by thomascorthals** [comment]
+1 to solve "SSL_ERROR_BAD_CERT_DOMAIN" on aliases.

**Comment by prupert** [comment]
+1

**Comment by oliver-graetz** [comment]
Currently the option to also use the www hostname exists. It wuld be very easy to just supply a textarea field where the admin could add arbitrary hostnames to also add in the certbot command. This should automatically work if all those hostnames are configured as domain aliases that point to the same webroot. This would remove the need to implement any more complicated detection of configured domain aliases for a certain domain. Sure, it's manual and it would be kind of a hack, but this could be implemented in a couple of minutes.

**Comment by StoneISStephan** [comment]
This is true if there is only one .well-known for all hostnames.
If each hostname requires a seperate .well-known file, the docroot needs to be known, even for domain aliases.

**Comment by oliver-graetz** [comment]
First of all, the .well-known is a directory, not a file. The certbot uses temp files in this directory for the domain verification challenge.

And I wrote just what you did: "if all those hostnames are configured as domain aliases that point to the same webroot". But for domain aliases, this is the common usage and the one case users currently need implemented.

**Comment by jult** [comment]
@StoneISStephan That can't work when you also have e-mail active for the domain name and its aliases, on that same Odin/Plesk instance. I'm also very surprised this isn't included, where's the code for this? How hard can it be to include a field for each of the alias domains on a Subscription? You can easily grab them from the plesk internal database. There's even a KB from odin for specifically that option. All we need is to have that offered in the same webform used for the main domain name. Of course, you require the alias domains to have all redirecting disabled for the moment of acme comms, but that's a user's responsibility, and default setting when you create a domain alias in plesk/odin panel, and easy to temp fix for the user.

**Comment by ninji** [comment]
+1

**Comment by n3roGit** [comment]
+1

**Comment by fabianfabian** [comment]
+1

**Comment by BastianBalthasarBux** [comment]
+1

**Comment by flergl** [comment]
+1 for adding support for aliases on certificates. Or at least enough changes that if the certificate with aliases is added manually the renewal process won't remove them.

**Comment by StVak** [comment]
+1

**Comment by akuehn** [comment]
+1

**Comment by Rar9** [comment]
This thead is open for 9 months and still nothing  :-)

**Comment by oliver-graetz** [comment]
Yes, and I have since switched to manually using Let's Encrypt for some machines. Two new servers didn't get Plesk licenses because this task wasn't resolved. The lack of improvement for this plugin is disturbing.

**Comment by steven-voorn** [comment]
+1

**Comment by RobinJespersen** [comment]
+1

**Comment by pubgrub** [comment]
+1!

**Comment by StVak** [comment]
For those who have access to view "Extensions" Menu, go under
Extensions > Let's Encrypt > Click subdomains and you can add certificate

**Comment by jtherin** [comment]
@StVak Ok for subdomain but it does not solve the problem with aliases...

**Comment by BastianBalthasarBux** [comment]
As the original post of StVak seems to be vanished, for those who are dealing with subdomains there is a very hidden solution (I re-add for those who stumble in via searchengine):

"For those who have access to view "Extensions" Menu, go under
Extensions > Let's Encrypt > Click subdomains and you can add certificate"

But like jtherin already told: This does not solve the problems with aliases.

**Comment by mbrammer** [comment]
# **+1**

**Comment by Daijobou** [comment]
+1

**Comment by ankn99** [comment]
+1

**Comment by BastianBalthasarBux** [comment]
For all those who are like me frustrated on that topic being not really treated: AFAICS Froxlor is able to do the task from within the GUI (but I did not test it yet by myself), and it looks much more lighter than the fatboy plesk! And guess what: it's FOSS (GPL)!

**Comment by Floezen** [comment]
+1

**Comment by No0ne** [comment]
+1

**Comment by jorfermo** [comment]
+1 for aliases

**Comment by Daijobou** [comment]
Thanks for this link.

**Comment by rvdb** [comment]
+1!

**Comment by juukie** [comment]
👍

**Comment by jult** [comment]
Good grief, is this still open? By now they're just stalling this, so their masters can earn some more money on certification that would otherwise be free. Come on, Odin. Don't be such a neo-con corporate slave for your paid cert masters.

**Comment by Daijobou** [comment]
to push this request you must voting for this one
https://plesk.uservoice.com/forums/184549-feature-suggestions/suggestions/15013254-let-s-encrypt-add-domain-aliases

**Comment by mcguffin** [comment]
+1

**Comment by JannoS** [comment]
+1

**Comment by EduardJS** [comment]
Any news on this one ? Seems like there's so many developers looking for it but nobody to care about the issue...

**Comment by webappbuilder** [comment]
+1

**Comment by der-eismann** [comment]
come on guys.... it's almost a year

**Comment by EduardJS** [comment]
@der-eismann Please vote it here as well: https://plesk.uservoice.com/forums/184549-feature-suggestions/suggestions/15013254-let-s-encrypt-add-domain-aliases

This is the only feature they don't reply on, even if other features with less votes got replied to..

**Comment by oliver-graetz** [comment]
Well, if they count on users using full domains instead of domain aliases (thus using up more of the licensed domains), then I can say no, that strategy doesn't work. We tell our customers that not being able to use Let's Encrypt for domain aliases is a limitation of Plesk. At the best, this manages to prevent our customers from licensing Plesk for other projects.

**Comment by EduardJS** [comment]
@oliver-graetz That's a very thinking strategy. 

The most important use of this request, from my personal stand-point is the ability to offer SSL for whitelabels.. 

I have two systems whitelabeled, which handle trnasactions, and SSL is a must.

We're basically stuck as we cannot offer SSL to our customers. How can I explain them, gents, the platform we chose in favor of cPanel does not want to offer SSL for aliased domains, as they're looking for their customers to fill up their maximum amount of domains, allowed by the type of license they pay for, in order to upgrade.

If that's the case, it's indeed dissapointing...
I wonder why features with less votes are being replied to, and this one which is crucial for some of us, are not even being looked at.

Even funnier is the fact that I pay for 3 WEB PRO editions... so there's no limit om the domains amount on neither of my servers.. so there's no strategy to accomplish there. Does that mean I'm a casualty ?

**Comment by Schouwenburg** [comment]
Maybe there is a developer who wants to implement this feature for some small funding...

**Comment by EduardJS** [comment]
https://www.facebook.com/Plesk/photos/a.430119390381141.99574.219640791429003/1230559103670495/?type=3&comment_id=1231469580246114

Asked about this on the official Plesk page. Hopefully someone replies and gets it the needed attention.

**Comment by BastianBalthasarBux** [comment]
It's ridiculous. I have 6 unlimited plesk installations ATM, but this is a real showstopper. I think nearly everybody has multidomain/multilanguage installations with content-sharing etc ... within one single CMS Installation. No need to have 10 logins, 10 installations which need to be technically supported etc ...
I will definitively switch to froxlor.

**Comment by petrus08** [comment]
Is one of most required feature, unfortunately nobody change something.

**Comment by Ogy** [comment]
+1

**Comment by Rar9** [comment]
We are coming close to 1 year of Waiting for support of Domain Alias.  

Has ANYONE found a easy to implement way to do this once MANUALLY?

**Comment by misaon** [comment]
👍 +1

**Comment by IronButterfly** [comment]
We are going to release support for domain aliases in LetsEncrypt extension in Q2, 2017.

**Comment by StoneISStephan** [comment]
@IronButterfly are you with Plesk?
Your account was created yesterday and has only 1 listed activity.

**Comment by IronButterfly** [comment]
@StoneISStephan yes, I'm from Plesk company.

**Comment by mbrammer** [comment]
Yes, he is. I wrote them on Twitter ;)
https://twitter.com/PleskHelps/status/808589013506461696
Thanks for your reply @IronButterfly

**Comment by AmaZili** [comment]
@IronButterfly hope the other issues listed here will be addressed as well : https://www.plesk.com/blog/lets-encrypt-plesk/#comment-29142
subdomains support is mandatory.... for proper mail support.

Thanks for taking care

**Comment by t0b3** [comment]
@IronButterfly will you also provide support for IDN (#132) in Q2 2017?

**Comment by IronButterfly** [comment]
@AmaZili yes, support of subdomains is considered in scope of LetsEncrypt improvements (Q2 2017) too.

**Comment by BastianBalthasarBux** [comment]
Q2 ... rocket science?
But thanks anyway. It is a really hard desired feature.
Race condition: Let's have a look who is faster, you implementing this, or me switching my servers to froxlor. ... *hrhr*

**Comment by marouanehassine** [comment]
+1 for aliases

**Comment by KirksFletcher** [comment]
Q2? Why, I am sure you can understand that this is not only a "nice to have" feature but for a LOT of users/hosts it is absolutely vital! it is such a simple tweak. I do not understand what issues you are having. May actually be time to move to Froxlor for sure! (I could even be tempted to stay if a valid workaround was provided until you fix!)

**Comment by KirksFletcher** [comment]
For those interested in a workaround (for now) is to: Instead of creating a domain alias, create a new domain within the webspace of the domain you wish to alias and set the document root to the usual document root (/public or /httpdocs) now you can apply a LE cert individually and still use the same codebase.

**Comment by StoneISStephan** [comment]
Keep in mind that this requires you to make all Apache / PHP Settings Changes to all Domains in this Subscription if they are all meant to run the same codebase.

It also adds a new Apache Vhost Conf for each of these sites.

**Comment by KirksFletcher** [comment]
StonelSStephan is correct, if you change php ver for example or allow short tags as another you must replicate that across all your domains. otherwise it works just fine as a workaround for now :-)

**Comment by brianhyper** [comment]
+1 I really really really fucking need this functionnality!!!

Go! go! go!

**Comment by lenar** [comment]
:thumbsup: +1

**Comment by Sybio** [comment]
I really need this too. Another brick in the wall :D ! +1

**Comment by escoand** [comment]
I've a workaround for that: create the new domain, create certificate for this domain, and set apache settings to:
```
SSLProxyEngine On
ProxyPass / https://my-other-domain.com/
ProxyPassReverse / https://my-other-domain.com/
ProxyRequests Off
```
maybe not the best solution but it's working

**Comment by atMaarten** [comment]
+1 for this, this would make everything a lot easier!

**Comment by radioboss** [comment]
Really needed feature. Lack of support for aliases prevents me from using LE extension :(

**Comment by fullsolucoes** [comment]
+1 with exactly same problem. Plesk windows.

**Comment by bradydan** [comment]
+1 can we please get an update on when this will be released?

**Comment by judgej** [comment]
+1 So what has been holding this up for two years? Lack of skills? A difficult problem to work around? Lack of incentivisation? Looking for a developer?

**Comment by wblondel** [comment]
Hi,

I see that a lot of people are not aware of the situation.

This feature is planned for Plesk Onyx Update.
It will be available within  about 3 weeks since now if everything goes right.

Source : https://plesk.uservoice.com/forums/184549-feature-suggestions/suggestions/15013254-let-s-encrypt-add-domain-aliases?tracking_code=6c3bc19635684e715a0e476806c73ed3

**Comment by judgej** [comment]
The web is moving in this direction, and so many people are relying on yoru Plesk services. Yet I see no urgency to get this one thing fixed. It's a tiny thing. But it's a **security** thing. You just don't mess with the security of your clients. There appears to be no explanation as to why this issue has been hanging around for so long, while paying customers are screaming for it. The link that has been provided is exactly the same - dozens of customers asking what is happening, with no response to keep any of them informed. It is such a shame the amount of bad feeling that can build up by being kept in the dark.

**Comment by wblondel** [comment]
I completely agree with you @judgej  :)

(I does not work for Plesk ^^)

**Comment by AmaZili** [comment]
@jugej Agree with you, security is not something we can let aside.
About security, there is no proper way to use a vpn connection with plesk (see https://talk.plesk.com/threads/openvpn-and-firewall-on-linux.342130/#post-821227 and request to vote for it on https://plesk.uservoice.com/forums/184549-feature-suggestions/suggestions/18554938-enhanced-vpn-support )

**Comment by rkosolapov** [comment]
Let’s Encrypt 2.0.0 extension with Domain Aliases support is now available!

https://ext.plesk.com/packages/f6847e61-33a7-4104-8dc9-d26a0183a8dd-letsencrypt

We would love to hear your feedback on our forum at http://talk.plesk.com. We’d like to thank everyone who commented on this request and provided invaluable feedback. Thanks!

**Comment by StoneISStephan** [comment]
This very good news!
Thanks for updating us here.

**Comment by wblondel** [comment]
You were faster than me @rkosolapov  ;)

**Comment by akuehn** [comment]
Hell freezes over.

**Comment by judgej** [comment]
That's wonderful, thank you.

There are a few "quirks" in the UI - should I report them here, or is there another channel for that?

**Comment by xgin** [comment]
As it was mentioned above the support of domain aliases was implemented in the extension version 2.0
Webmail and other services are not considered as 'aliases'. Another issues were already created about them. We cannot implement all at once, but we are working on one by one. Please, wait for the next releases.
I am closing the issue without a twinge of conscience.
Feel free to open new issues about problems or remarks.

**Comment by vijayanand007** [comment]
i have a website and it is city based website. i.e domain.com shows all city ads and *.domain.com alias will produce city based website like city.domain.com, city2.domain.com....so on.  so i want to add ssl for *.domain.com also so help me to create it

**Comment by oliver-graetz** [comment]
Let's Encrypt doesn't yet support wildcards for certificates. Also, when support comes next year, the challenge to prove control over all subdomains of a domain will be much different than the one currently used. So don't count on this feature being available for the Plesk extension anytime soon. If you need a wildcard certificate now, you need to buy one from another certificate provider.

**Comment by sanderdewijs** [comment]
One issue I just ran into when creating SSL certs for my domain aliases is that when you add a new alias, all the other certs of the main domain are renewed in the process. As I have 6500 aliases this results in an error as soon as I reach 100 active SSL certs. If I add another one, all the existing certs are added in the CSR, which throws this error: "Detail: Error creating new cert :: CSR contains more than 100 DNS names"

Wouldn't is be better to just include the newly added aliases in the CSR instead of all the aliases that already have a valid certificate? Also performance wise this would be preferable, as requesting certs is pretty slow in this setup.
