### ISSUE TITLE
Certificate for subdomain

### ISSUE THREAD

**Issue by mgascoyne** [plesk/letsencrypt-plesk#29]
If i want to get an certificate for an subdomain e.g. mysubdomain.domain.tld the extension wants to renew the certificate for domain.tld and not create a new certificate for the subdomain.

**Comment by mrclschstr** [comment]
See #19

**Comment by JHGitty** [comment]
@mrclschstr As I understand the issue #19 is about a single certificate for multiple subdomains.
@mgascoyne I cannot reproduce the issue.

I have 3 domains:
www.example.com
test.example.com
test2.example.com

After the usage of the Lets Encrypt extension I'll have 3 certificates - one for each (sub)domain. *It works fine*. There will no certificate be overriden.

**Comment by xgin** [comment]
@mgascoyne Could you provide your actions step by step? Because I cannot reproduce the issue too.

**Comment by Natim** [comment]
To have them all on the same certificate:

    ./letsencrypt-auto certonly --webroot -w /var/www/example -d example.com -d www.example.com -w /var/www/thing -d thing.is -d m.thing.is

To create a certificate for each:

    ./letsencrypt-auto certonly --webroot -w /var/www/mysubdomain -d mysubdomain.domain.tld
    ./letsencrypt-auto certonly --webroot  -w /var/www/domain -d www.domain.tld -d domain.tld

**Comment by xgin** [comment]
Close because cannot reproduce and there is no additional details from requestor.

**Comment by umsch** [comment]
Hey everyone. I see this is an old thing but i am running into it since one of the last plesk updates.
My issue is that I only hosting the subdomain using Plesk. The main domain is beeing hosted on another server. 
(e.G.) mydomain.tld : 10.10.10.10
subdomain.mydomain.tld (123.123.123)

Letsencrypt should be able to fail on domains and continue with subdomains.

**Comment by Natim** [comment]
@umsch have you tried:

```./letsencrypt-auto certonly --webroot -w /var/www/mysubdomain -d mysubdomain.domain.tld``` ?

**Comment by umsch** [comment]
yes. this works. But I like it to be updated by Plesk. I don't like to add a cron job because it may be an issue someday.
