### ISSUE TITLE
Port 8443 (HTTPS) self connection issue

### ISSUE THREAD

**Issue by Jackysi** [plesk/letsencrypt-plesk#31]
The PERL script located **/opt/psa/var/modules/letsencrypt/venv.VJFRQ/lib/python2.7/site-packages/letsencrypt_plesk/api_client.py** is set to port **8443**. Now I didn't read all the script/plugin and research how it works but some people/hosts use alternative GUI port with disabled port **8443** or under firewall. I was unable to use this extension until changing the port to my interface port.

Q: Is it possible to detect Plesk (API?) port prior attempting connection? 
**THANK YOU for this awesome extension it makes Certificates issuing EXTREMELY EASY!**

**Comment by MatrixCrawler** [comment]
Probably relates to #30

**Comment by Jackysi** [comment]
Yeah seems to be the same issue, my apologies for duplicate.
