### ISSUE TITLE
Install certificate failure: Unable to set certificate name :

### ISSUE THREAD

**Issue by grunsch** [plesk/letsencrypt-plesk#32]
If I try to renew the certificate I get this error message:

> Install certificate failure: Unable to set certificate name :

The certificate is renewed from them and stored on the server but the update in plesk failes

**Comment by xgin** [comment]
@grunsch does the error occur for every your domain? or the specific one? may be subdomain? we need more details to reproduce the issue.

**Comment by Novaal** [comment]
I'm having the same issue with a subdomain. I would test more, but my domain reached the limit of 5 request in the past 7 days.

```
Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: 2015-12-13 14:55:55,100:WARNING:letsencrypt.cli:Root (sudo) is required to run most of letsencrypt functionality.
Install certificate failure: Unable to set certificate name :
IMPORTANT NOTES:
- Congratulations! Your certificate and chain have been saved at /opt
/psa/var/modules/letsencrypt/etc/live/subdomain.example.com/fullchain.pe
m. Your cert will expire on 2016-03-12. To obtain a new version of
the certificate in the future, simply run Let's Encrypt again.
```

Perhabs it is caused by my Apache rewrite rule?

```
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteCond %{REQUEST_URI} !^/.well-known/
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
```

**Comment by grunsch** [comment]
@xgin it is on every subdomain I tried. I did only try with subdomains until now, but on my site I tried without any .htacces, rewrite-rule or something else which could interfere.

**Comment by xgin** [comment]
The same issue is #7 - is going to be fixed in Plesk 12.5.30 Update 15
Please install updates and check again

**Comment by grunsch** [comment]
I'm on 12.5.30 Update 14 and seems to be the latest to me:
http://docs.plesk.com/release-notes/12.5/change-log/
Do I need to activate Early Adaptor Baseline?

**Comment by xgin** [comment]
@grunsch nope, just run `plesk installer` manually. Or wait for about a week - it will be installed automatically.

**Comment by grunsch** [comment]
Works now!
Thanks
