### ISSUE TITLE
Root is required issue on migrated Domain

### ISSUE THREAD

**Issue by offisy** [plesk/letsencrypt-plesk#35]
Hi Guys,

on most of the domains, letsencrypt works fine. Thanks!
But I migrated a domain from another plesk server and I got following error message during the certification process:

> _Root (sudo) is required to run most of letsencrypt functionality_

Is it possible that I need to change some rights before using letsencrypt? I had several problems to import the mailboxes. Perhaps some other rights are missing, too.

**Comment by xgin** [comment]
Hi @offisy
The message about root is just a warning, it is always displayed.
There are more error messages below - it should shed the light on the root cause of the failure.

**Comment by Natim** [comment]
Today @letsencrypt will store your certificate and its configuration for later renewal in ``/etc/letsencrypt`` it should be accessible by root only for security reasons.

**Comment by xgin** [comment]
@Natim That is not correct in the context of Plesk plugin.
Special user `psaadm` has access to the certificates location `/usr/local/psa/var/modules/letsencrypt/etc/`
The utility should not be executed with root privileges because it makes inoperable from Plesk UI.

**Comment by xgin** [comment]
The warning "Root (sudo) is required" was removed from letsencrypt.
