### ISSUE TITLE
Create cert for webmail

### ISSUE THREAD

**Issue by ntimo** [plesk/letsencrypt-plesk#37]
Hello,

could you please add support for creating certificates for the webmail subdomain? So we can use the webmail securly.

**Comment by EarMaster** [comment]
See #19

**Comment by psyopussy** [comment]
@earmaster, #19 is about SAN's...

anyway,
is there a way to get a cert for the default plesk webmail.mydomein.tld subdomain?

**Comment by ankn99** [comment]
I would love to see this too ....

sincerly

**Comment by ralerbon** [comment]
I have found a workaround as long as the plugin doesn't support the "real" webmail adress.

http://guido.vonrudorff.de/secure-plesk-webmail-with-ssl/

But on Point .4 it should be HTTPS not HTTP (and the mail.domain.tld was (for me) pre-configured with an A Record for imap and smtp. Have a look on your DNS Template to figured out what of domains are autogeneratet.

 I am ashamed for my bad English. ;)

![apache](https://cloud.githubusercontent.com/assets/9945917/16962400/acdfe96c-4df1-11e6-834e-9ad0bb1628c1.png)

**Comment by Liwindo** [comment]
This function is now more important than ever because StartCom will be banned by Mozilla in the near future. So please solve it!

**Comment by Ogy** [comment]
bump

**Comment by cutzenfriend** [comment]
Bump!! This is needed so badly...

**Comment by discostur** [comment]
Shouldn't be too tricky, or? Just pass an additional subdomain to the letsencrypt-api:

webmail.domain.tld

**Comment by tofuSCHNITZEL** [comment]
There already is an option to include www.<domain> as a SAN so I propose the following:
For Plesk Onyx (because only in Plesk Onyx you can set a custom cert for webmail) display following option below the "Include www... as an alternative domain name"
[checkbox] Include webmail.<domain> as an alternative domain name. 
this will make an additional plesk letsencrypt API call analogue to adding the www SAN
if possible it could automatically set the certificate to be used under Mail Settings->SSL/TLS certificate for webmail

unfortunately the files you get from ext.plesk.com are encrypted so I cannot add the changes myself. And without seeing the code used to call the python scripts I cannot add the code for the webmail SAN to my fork of this repo.

**Comment by Liwindo** [comment]
Seems they don't want to implement this feature. Would be interesting to know why...

**Comment by Ogy** [comment]
it is not a good idea to have one certificate with a lot of alternatives names
maybe letsencrypt even doesn't support it for security reasons

## What they should implement is auto generated ssl for address from MX record and other generic services
+1 for user-defined

**Comment by StAn187** [comment]
Looks like the implemented this in Version 17

**Comment by MaxMcBurn** [comment]
+1

**Comment by Ogy** [comment]
@StAn187 Hi, can you, please, tell me a short howto? I still see only include www.@ and automaticaly it doesn't request certificate for webmail.@
[root@plesk ~]# cat /etc/plesk-release
17.0.17 cos7.build1700161028.14

**Comment by popothemes** [comment]
Hello

I am using 
[root@plesk ~]# cat /etc/plesk-release
17.0.17 cos7.build1700161028.14

I tried to create certificate with this command 
sudo -u psaadm bash /usr/local/psa/admin/plib/modules/letsencrypt/scripts/le-run -d domain.com -d www.domain.com -d webmail.domain.com -d mail.domain.com -d imap.domain.com -d smtp.domain.com

But unfortunate no luck for webmail certification creation its got with following error 


[root@server ~]# sudo -u psaadm bash /usr/local/psa/admin/plib/modules/letsencrypt/scripts/le-run -d domain.com -d www.domain.com -d webmail.domain.com -d mail.domain.com -d imap.domain.com -d smtp.domain.com
Warning: Current locale is unusable. Using 'C' instead.

[2017-03-04 15:41:24] ERR [extension/letsencrypt] Execution of /usr/local/psa/admin/plib/modules/letsencrypt/scripts/cli.php failed with exit code 1 and the output:
Saving debug log to /usr/local/psa/var/modules/letsencrypt/logs/letsencrypt.log
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for domain.com
http-01 challenge for www.domain.com
http-01 challenge for webmail.domain.com
http-01 challenge for mail.domain.com
http-01 challenge for imap.domain.com
http-01 challenge for smtp.domain.com
Starting new HTTPS connection (1): 127.0.0.1
Starting new HTTPS connection (1): 127.0.0.1
Cleaning up challenges
Site "webmail.domain.com" get failure: Site does not exist
Execution of /usr/local/psa/admin/plib/modules/letsencrypt/scripts/cli.php failed with exit code 1 and the output:
Saving debug log to /usr/local/psa/var/modules/letsencrypt/logs/letsencrypt.log
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for domain.com
http-01 challenge for www.domain.com
http-01 challenge for webmail.domain.com
http-01 challenge for mail.domain.com
http-01 challenge for imap.domain.com
http-01 challenge for smtp.domain.com
Starting new HTTPS connection (1): 127.0.0.1
Starting new HTTPS connection (1): 127.0.0.1
Cleaning up challenges
Site "webmail.domain.com" get failure: Site does not exist

exit status 1
[root@server ~]#

**Comment by ctron** [comment]
Is there any update on this issue?

**Comment by BitElysium** [comment]
They are dragging their but behind the short bus to fix this!

**Comment by xgin** [comment]
It is possible to secure webmail with the extension version 2.1.0
Plesk Onyx is minimal required version for the feature.
