### ISSUE TITLE
SSL for Plesk IP

### ISSUE THREAD

**Issue by eladnova** [plesk/letsencrypt-plesk#43]
Is it possible to secure my Plesk CP if I access it via an IP address and not a domain name?

IE I access my CP via XXX.XX.X.XXX:8443

**Comment by xgin** [comment]
It is the restriction of Let's Encrypt CA: https://community.letsencrypt.org/t/certificate-for-public-ip-without-domain-name/6082 and https://community.letsencrypt.org/t/certificate-for-static-ip/84
