### ISSUE TITLE
Have console command for automated deployment.

### ISSUE THREAD

**Issue by MeanEYE** [plesk/letsencrypt-plesk#46]
We use Ansible to deploy our sites. Right now after deploying we have to go and manually add certificate to the domain. It would be of great help if we could just call `/usr/shared/psa/bin/letsencrypt <subscription>` and have it created during deployment process automatically.

**Comment by xgin** [comment]
Run the utility:
```
plesk bin extension --exec letsencrypt cli.php -d domain.com -d www.domain.com
```
See additional notes:
https://github.com/plesk/letsencrypt-plesk/wiki/Command-Line-Interface

**Comment by MeanEYE** [comment]
@xgin thanks for replying. Is there any downside to run the command multiple times?

**Comment by xgin** [comment]
@MeanEYE there are rate limits you could reach: https://community.letsencrypt.org/t/rate-limits-for-lets-encrypt/6769
> Certificates/Domain you could run into through repeated re-issuance. This limit measures certificates issued for a given combination of Public Suffix + Domain (a "registered domain"). This is limited to 5 certificates per domain per week.

**Comment by MeanEYE** [comment]
@xgin does running this command with same domain name as parameter renews the certificate? If so, I'll probably have to put some checks in place to make sure certificate is generated only once.

**Comment by xgin** [comment]
@MeanEYE yes, it does

**Comment by MeanEYE** [comment]
Okay, thanks that's what I wanted to know!
