### ISSUE TITLE
Installation failed with error in ndg-httpsclient

### ISSUE THREAD

**Issue by ToEvenStay** [plesk/letsencrypt-plesk#57]
Hello i have a problem when i have installed let's encrypt extension in plesk 12.5 on debian 8 and full install .

Here the error : 
Échec de l'installation de l'extension : Executing /opt/psa/admin/plib/modules/letsencrypt/scripts/post-install.php failed: Bootstrapping dependencies for debian jessie... Selecting previously unselected package plesk-letsencrypt-pre. (Reading database ... (Reading database ... 5% (Reading database ... 10% (Reading database ... 15% (Reading database ... 20% (Reading database ... 25% (Reading database ... 30% (Reading database ... 35% (Reading database ... 40% (Reading database ... 45% (Reading database ... 50% (Reading database ... 55% (Reading database ... 60% (Reading database ... 65% (Reading database ... 70% (Reading database ... 75% (Reading database ... 80% (Reading database ... 85% (Reading database ... 90% (Reading database ... 95% (Reading database ... 100% (Reading database ... 158251 files and directories currently installed.) Preparing to unpack .../plesk-letsencrypt-pre_1.0.0-debian8.0.15112715_amd64.deb ... Unpacking plesk-letsencrypt-pre (1.0.0-debian8.0.15112715) ... Setting up plesk-letsencrypt-pre (1.0.0-debian8.0.15112715) ... Creating virtual environment... Updating letsencrypt and virtual environment dependencies... Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-UuwUIV/ndg-httpsclient 

Thanks in advance for your help , i speak french sorry for my bad english .

**Comment by xgin** [comment]
Hey @ToEvenStay please run:
```PLESK_DEBUG=1 /opt/psa/admin/sbin/modules/letsencrypt/le-installer```
It will display more details about packages installation.
Because now it is not clear what's wrong with it.

**Comment by ToEvenStay** [comment]
Thanks @xgin he block here : 
![capture](https://cloud.githubusercontent.com/assets/13045598/12215462/9f7f1dae-b6bd-11e5-964a-1bbd6bd64655.PNG)

**Comment by xgin** [comment]
There is no problem on your screenshot.
Was it successfully done?
Or were there some errors further?

**Comment by ToEvenStay** [comment]
@xgin no, he finished at 99% and there was nothing more
Here error but with screenshot : 
![capture1](https://cloud.githubusercontent.com/assets/13045598/12215555/d6baadfc-b6c1-11e5-8f41-7d65718fc7ae.PNG)
![capture2](https://cloud.githubusercontent.com/assets/13045598/12215554/d6b9e16a-b6c1-11e5-8064-aa4f1678f804.PNG)

**Comment by xgin** [comment]
It looks like network issue on your server.
Let's try installation from my mirror:
```PIP_INDEX_URL=https://pypi.ekazakov.ru/simple PLESK_DEBUG=1 /opt/psa/admin/sbin/modules/letsencrypt/le-installer```

**Comment by ToEvenStay** [comment]
@xgin Thanks you very mutch to hepm me but i get also a error : 
![capture3](https://cloud.githubusercontent.com/assets/13045598/12218127/2459c7f6-b716-11e5-9d96-6ccfc20f3b4d.PNG)

Would you like a acces to my server ? Thanks very to help me .

**Comment by xgin** [comment]
Yeah, it will save time. Contact me with email, please.

**Comment by ToEvenStay** [comment]
Ok i have send you thanks .

**Comment by xgin** [comment]
The issue is caused by Virtuozzo hardware node misconfiguration - processes are killed by OOM.
