### ISSUE TITLE
Certificate generation fails with custom DocumentRoot

### ISSUE THREAD

**Issue by mattsims** [plesk/letsencrypt-plesk#58]
We use Capistrano to deploy sites to Plesk, which keeps previous deployments in folders on the server and references the current (latest) deployment folder via a 'current' symlink under the document root ([example here](http://capistranorb.com/documentation/getting-started/structure/)).  As such, we reconfigure the Apache DocumentRoot via the Plesk 'Apache & nginx Settings' panel to be this symlink, i.e.:

    DocumentRoot "/var/www/vhosts/getcodee.co.uk/httpdocs/current"

Screenshot: http://cloud.deucecreative.co.uk/0w0b1Y1D1Y1g

Unfortunately, certificate generation fails when this non-standard DocumentRoot is used ([screenshot of error](http://cloud.deucecreative.co.uk/1H3W3u2p3D37)).

Temporarily removing the custom directives allows the certificate to be generated successfully.

**Comment by xgin** [comment]
@mattsims why don't you set relative path to the symlink (`httpdocs/current` in your case) in `Hosting Settings` > `Document root`?
I also use Capistrano for RoR projects and never set DocumentRoot in Apache settings.

**Comment by mattsims** [comment]
@xgin Good thinking – that works! Thanks :+1:
