### ISSUE TITLE
Segmentation fault while creating a new certificate

### ISSUE THREAD

**Issue by sebas** [plesk/letsencrypt-plesk#59]
When I try to create a new certificate I get:

Error: Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: /usr/local/psa/var/modules/letsencrypt/venv.BADTz/lib/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
DeprecationWarning
/usr/local/psa/admin/plib/modules/letsencrypt/scripts/le-run: line 23: 14371 Segmentation fault &quot;$LE_HOME/venv/bin/letsencrypt&quot; $config --renew-by-default --no-redirect --agree-tos --text --config-dir &quot;${LE_HOME}/etc&quot; --work-dir &quot;${LE_HOME}/lib&quot; --logs-dir &quot;${LE_HOME}/logs&quot; --authenticator letsencrypt-plesk:plesk --installer letsencrypt-plesk:plesk $@

I am using:
OS	‪CentOS 6.7 (Final)‬
Plesk version	12.5.30 Update #17
Let's Encrypt	1.2-1

Thanks for your help.

**Comment by xgin** [comment]
Hey, we need to find more details about failure.
Please run `strace /usr/local/psa/var/modules/letsencrypt/venv/bin/letsencrypt --text`

**Comment by sebas** [comment]
Here is the log from it.

[letsencrypt_strace.zip](https://github.com/plesk/letsencrypt-plesk/files/92540/letsencrypt_strace.zip)

**Comment by xgin** [comment]
We have released a new version 1.6 of the extension.
Major change is a switch from system python to plesk-py27 on all unix OSes.
Distribution of own python should increase installation reliability and resolve the issue.
Please, check your installation with the latest update.
Feel free to reopen the issue if the problem is still reproduced.
