### ISSUE TITLE
Can't install module on Plesk 12.5 on CentOS 7

### ISSUE THREAD

**Issue by zorrobyte** [plesk/letsencrypt-plesk#61]
Error: Failed to install the extension: Executing /usr/local/psa/admin/plib/modules/letsencrypt/scripts/post-install.php failed: Bootstrapping dependencies for centos 7 x86_64... http://autoinstall.plesk.com/LETSENCRYPT_0.0.1/dist-rpm-CentOS-7-x86_64/packages/plesk-wheel-psutil-3.2.2-centos7.15112714.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=plesk-letsencrypt clean metadata Trying other mirror. http://autoinstall.plesk.com/LETSENCRYPT_0.0.1/dist-rpm-CentOS-7-x86_64/packages/plesk-wheel-cryptography-1.1-centos7.15112714.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=plesk-letsencrypt clean metadata Trying other mirror. Error downloading packages: plesk-wheel-psutil-3.2.2-centos7.15112714.x86_64: [Errno 256] No more mirrors to try. plesk-wheel-cryptography-1.1-centos7.15112714.x86_64: [Errno 256] No more mirrors to try.

**Comment by lucer** [comment]
Hello,

A yum metadata doesn't updated on server, I re-regerate it. Please try again or download from catalog and upload to Plesk again if it was installed before.

Thanks,

**Comment by zorrobyte** [comment]
Works fine now, thanks!
