### ISSUE TITLE
Can't renew certificate with forced SSL connection or BasicAuth

### ISSUE THREAD

**Issue by FlipZoomMedia** [plesk/letsencrypt-plesk#63]
I can not renew the certificates. The cronjob produce errors. Also, when I try this manually via the Extension. It is up to two things:

- A forced SSL connection to the domain. In Plesk "Additional directives for HTTP (Apache)":
```
RewriteEngine on
RewriteCond %{HTTPS} !=on
RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [QSA,R=301,L]
```

- And through Plesk applied password protection on the domain.

I have no .htaccess file in the folder. Any additional web server configurations are made through Plesk. I have admin access, but am not a root user (Managed Server). 

I get the following error messages (with Forced SSL and password protection):
```
Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: 2016-01-19 13:56:07,885:WARNING:letsencrypt.cli:Root (sudo) is required to run most of letsencrypt functionality.
Failed authorization procedure. removed.domain.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://removed.domain.com/.well-known/acme-challenge/REMOVED-ID [REMOVED IP]: 401
IMPORTANT NOTES:
- The following errors were reported by the server:

Domain: removed.domain.com
Type: urn:acme:error:unauthorized
Detail: Invalid response from http://removed.domain.com
/.well-known/acme-
challenge/REMOVED-ID
[REMOVED IP]: 401
```
Because there is a development environment on the subdomain, password protection is absolutely necessary. Also forced SSL connection. If I remove the password protection and the forced connection, the certificate will be renewed without any problems.

Extension Version: 1.2-1
Plesk-Version: 12.5.30 Update 18
OS: 	‪CentOS Linux 7.2.1511 (Core)‬

Is there a workaround?

**Comment by xgin** [comment]
As a workaround create an empty .htaccess file, the plugin checks for existence

**Comment by FlipZoomMedia** [comment]
Thank you. The trick worked. Do you plan to fix the problem yet, so I do not have to communicate with customers so if everything is done via Plesk?

Now I get, however, still following error:
```php
PHP Warning: Invalid argument supplied for foreach(); File: /usr/local/psa/admin/plib/modules/letsencrypt/library/Helper/DomainManipulator.php, Line: 26
```

**Comment by grunsch** [comment]
@xgin Why not removing the check of existing .htaccess file and always put the .htaccess file from the script to the verifypath?
