### ISSUE TITLE
Generate SSL for plesk interface

### ISSUE THREAD

**Issue by Caroga** [plesk/letsencrypt-plesk#65]
Hi,

Is it possible to generate a SSL certificate for the default Plesk installation ? 
Currently my installation is under https://vps.domain.tld:8880, but I'd like to use a certificate for this.

Kind regards,
Caroga

**Comment by DavidAkroyd** [comment]
Currently this works fine on port 8443, see issue #11 - I am unsure about other ports

**Comment by xgin** [comment]
Are you sure, the URL in browser is **https**://vps.domain.tld:8880?
By default port 8880 is HTTP - it is not secure connection and cannot use certificate.
May be you should use **https**://vps.domain.tld:**8443** for default installation.

The fix of #30 allows customised ports to be secured.

**Comment by Caroga** [comment]
I will see if I can change the port to 8443 for the default installation of the Plesk Web Interface. 
If so, and #11 and/or #30 address the situation I would like to create, I will mark this as closed and provide a "how to" for it, if wanted.
Thanks in advance!

**Comment by Caroga** [comment]
Fixed. 
Eventually I went with the advice from @xgin ( #11 ).
I created a subdomain `plesk.domain.tld`.
Changed plesk settings to match this domain.
Browsed towards `plesk.domain.tld:8443`.
Generated SSL cert from inside the subdomain, enabled checkbox to use the cert for securing plesk as well.
Profit.

thank you!
