### ISSUE TITLE
Unable to set certificate name

### ISSUE THREAD

**Issue by shyper-ideler** [plesk/letsencrypt-plesk#7]
Hello,
i am unable to update/install an certificate for an subdomain. The Plesk-API responses with this error:
Install certificate failure: Unable to set certificate name :

**Comment by xgin** [comment]
This is a known issue in Plesk API.
I hope it will be fixed in one of the next updates, but I cannot guarantee it.

**Comment by shyper-ideler** [comment]
Installed latest Plesk update and now it works. Thank you!
