### ISSUE TITLE
Python 2.6 deprecation warning, even if 3.3 is installed and enabled

### ISSUE THREAD

**Issue by maltris** [plesk/letsencrypt-plesk#71]
I think the creator of #70 is trying to say the same, but hes neither providing the correct output nor any further related information. I will.

I'm running CentOS 6 with Python 3.3 from the  "Software Collections"-project.
The error-message looks like:

    /usr/local/psa/var/modules/letsencrypt/xxxx.xxxxx/lib/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
    DeprecationWarning

How can I let LE know that there is Python 3.3 installed and available?

**Comment by xgin** [comment]
Python 3.x is not officially supported.
You should know that 2.7 could be newer than 3.3 because branches 2.x and 3.x are developed in parallel.
Python 3.3 is rather old, actual version is 3.5.1 (and 2.7.11)
