### ISSUE TITLE
Automatic renewal for certificate inlcuding the www alias does not work correctly

### ISSUE THREAD

**Issue by MatrixCrawler** [plesk/letsencrypt-plesk#72]
I just realised, that the automatic renewal for the certificates that are requested with the www. alias does not work correctly.
The renewed cert is only valid for the domain.tld and not for www.domain.tld

You'll need to renew the certificate manually including the www. alias

**Comment by xgin** [comment]
Did you initially run letsencrypt from CLI or from Plesk UI?

**Comment by MatrixCrawler** [comment]
Plesk UI

**Comment by xgin** [comment]
Since version 2.0 renew process retrieves alternative names from the previous certificate.
The issue is not actual anymore.
