### ISSUE TITLE
Not work at no domain and no other webspace.

### ISSUE THREAD

**Issue by Gamerios** [plesk/letsencrypt-plesk#73]
It work at no domain also not at different webspace.

It has an infinite loading loop.

Screenshot:
https://i.gyazo.com/c94b7ead50a93fda96124677a606b827.png

Anyone know what todo ?

Regards

**Comment by Gamerios** [comment]
Now i also changed permissions of letsencrypt plesk module folder to root and 777 and to psaadm 777  but always get then this:

https://gyazo.com/7afbcba0fd8a4239b9c96ca16899d8f0



**if remove and install plugin again i get again the unlimited / infinite loading loop / hangs at loading after click install certificate
**
It has an infinite loading loop.

Screenshot:
https://i.gyazo.com/c94b7ead50a93fda96124677a606b827.png

**can anyone help ?**

Regards

**Comment by xgin** [comment]
We reworked the codebase and improved error handling in the version 2.0
Please, try the latest extension and feel free to reopen the issue with new details.
