### ISSUE TITLE
Error on Subdomains

### ISSUE THREAD

**Issue by scysys** [plesk/letsencrypt-plesk#75]
Subdomain Certificates seems to be working fine. But when activate the Let´s Encrypt Certificate with installed Nginx Proxy, there comes to errors in Browser. "502 Bad Gateway".

Only on Subdomains. Main Domain is working fine.

**Comment by Liwindo** [comment]
I have the same configuration and can't confirm the error. Could you give some more information?

**Comment by scysys** [comment]
Error inside Plesk Protocoll:

11889#0: *57730 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream
AH02261: Re-negotiation handshake failed: Not accepted by client!?, referer: xxx

No other Error Logs.
Plesk v12.5.30_build1205150826.19 os_Ubuntu 14.04
Don´t get it to work with Nginx installed.

**Comment by scysys** [comment]
Found Error.

It occurs, when User Account has not filled out Adress Details. I use an external System to create Accounts in Plesk, and then there are no Account Details like Street and so on filled out.
