### ISSUE TITLE
How to? "Corrupted meta.xml file."

### ISSUE THREAD

**Issue by ygde** [plesk/letsencrypt-plesk#8]
Betriebssystem 	‪CentOS 6.7 (Final)‬
Plesk Version 	12.5.30 Update #12

I am trying to add this ls plesk module / extension ... Error Message: "Corrupted meta.xml file."

**Comment by Huskynarr** [comment]
I have the Same Problem.

Try the *letsencrypt-auto* that have worked by me.

**Comment by xgin** [comment]
The repository is not a Plesk extension, but a CLI utility extending `letsencrypt` with Plesk API.
Please wait for an official announcement of the extension.
I am going to close the issue with README update soon.
