### ISSUE TITLE
403 Error on Pimary Domain event with Manual .htaccess override

### ISSUE THREAD

**Issue by thezenmonkey** [plesk/letsencrypt-plesk#82]
I'm still getting the 403 error on my primary domain even when I manaully add the /.well-known/acme-challenge/.htaccess 

The install process delete's the .htaccess.  I've tried removing my root .htaccess as well. At firsty I thought it was because I was using apache + nginx in proxy mode, but the install worked on a subdomain.

**Comment by xgin** [comment]
Hey, @thezenmonkey 
The workaround I advised in #63 was to put `.htaccess` in the domain's root, because the plugin should put the generated `.htaccess` file in the acme-challenge by itself. Anyway the plugin was improved and a stub file is no longer required.
Please, check out a new version of the extension.

**Comment by thezenmonkey** [comment]
I tried that, I cleared all custom apache and nginx directives set in Plesk and it threw a 500 error. I'm not sure if the CMS is causing issues but with rewrites it shoudl be avoiding the CMS .I ended up temporarily pointing the domain to an empty directory, installing and then switching back. Hopefully it renews OK.

For reverence here is the error I got
```
Error: Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: Failed authorization procedure. www.domain.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://www.intellijointsurgical.com/.well-known/acme-challenge/DNm7J5t37m-eIu2EoWzyEAZwzDvaq-Z4t3Eh8THOkZU [IP]: 500, domain.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://domain/.well-known/acme-challenge/d4ZKQB9ai_f3kL31Ljp7JtFpBQyG4YkZFwInhtPLFr0 [IP]: 500
IMPORTANT NOTES:
- The following errors were reported by the server:

Domain: www.domain.com
Type: unauthorized
Detail: Invalid response from http://www.domain.com
/.well-known/acme-challenge/DNm7J5t37m-eIu2EoWzyEAZwzDvaq-
Z4t3Eh8THOkZU [IP]: 500

Domain: intellijointsurgical.com
Type: unauthorized
Detail: Invalid response from http://domain.com
/.well-known/acme-
challenge/d4ZKQB9ai_f3kL31Ljp7JtFpBQyG4YkZFwInhtPLFr0
[IP]: 500

To fix these errors, please make sure that your domain name was
entered correctly and the DNS A record(s) for that domain
contain(s) the right IP address.
```

**Comment by xgin** [comment]
There are a lot of reasons causing the error code 500.
It could be either a conflict of plugin's `.htaccess` with server settings or domain's misconfiguration in Plesk.
Could you check Apache and nginx error logs during the certificate renewal.
Log-browser in Plesk might be very useful here.

**Comment by thezenmonkey** [comment]
Ok looks like 1.5 works. The last issue was between the keyboard and the chair. Thanks
