### ISSUE TITLE
An unexpected error occurred:

### ISSUE THREAD

**Issue by floewe** [plesk/letsencrypt-plesk#85]
I got an error running the plugin in the bash:

[root@web ~]# /usr/local/psa/var/modules/letsencrypt/venv/bin/letsencrypt
An unexpected error occurred:
ContextualVersionConflict: (cryptography 1.1 (/usr/local/psa/var/modules/letsencrypt/venv.7nNoz/lib/python2.7/site-packages), Requirement.parse('cryptography>=1.3'), set(['PyOpenSSL']))
Please see the logfile 'letsencrypt.log' for more details.
[root@web ~]#

Using Plesk in a browser it Looks like:
Error: Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: Traceback (most recent call last):
 File &quot;/usr/local/psa/var/modules/letsencrypt/venv/bin/letsencrypt&quot;, line 11, in &lt;module&gt;
 sys.exit(main())
 File &quot;/usr/local/psa/var/modules/letsencrypt/venv.7nNoz/lib/python2.7/site-packages/letsencrypt/cli.py&quot;, line 1950, in main
 plugins = plugins_disco.PluginsRegistry.find_all()
 File &quot;/usr/local/psa/var/modules/letsencrypt/venv.7nNoz/lib/python2.7/site-packages/letsencrypt/plugins/disco.py&quot;, line 168, in find_all
 plugin_ep = PluginEntryPoint(entry_point)
 File &quot;/usr/local/psa/var/modules/letsencrypt/venv.7nNoz/lib/python2.7/site-packages/letsencrypt/plugins/disco.py&quot;, line 31, in __init__
 self.plugin_cls = entry_point.load()
 File &quot;/usr/local/psa/var/modules/letsencrypt/venv.7nNoz/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 2201, in load
 self.require(*args, **kwargs)
 File &quot;/usr/local/psa/var/modules/letsencrypt/venv.7nNoz/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 2218, in require
 items = working_set.resolve(reqs, env, installer)
 File &quot;/usr/local/psa/var/modules/letsencrypt/venv.7nNoz/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 835, in resolve
 raise VersionConflict(dist, req).with_context(dependent_req)
 ContextualVersionConflict: (cryptography 1.1 (/usr/local/psa/var/modules/letsencrypt/venv.7nNoz/lib/python2.7/site-packages), Requirement.parse('cryptography&gt;=1.3'), set(['PyOpenSSL']))

I use plesk 12.5.30 with CENTOS 7. According to 
https://community.letsencrypt.org/t/plesk-12-5-debian-7-9-error-by-create-a-ssl/12809
other People using Debian and Ubuntu had the same problem.

**Comment by mv-T** [comment]
pls see https://github.com/plesk/letsencrypt-plesk/issues/86

**Comment by lucer** [comment]
We updated cffi to 1.5.2 and cryptography to 1.3.1, you need to reinstall the extension, or re-run /usr/local/psa/admin/bin/modules/letsencrypt/le-installer
