### ISSUE TITLE
plesk 12.5.30 update #25 error

### ISSUE THREAD

**Issue by LairdWalker** [plesk/letsencrypt-plesk#86]
I am running 
Version	Plesk v12.5.30_build1205150826.19 os_Ubuntu 14.04
OS	        Ubuntu 14.04.4 LTS

when i install the plugin it installs just fine its when i go to add a new ssl or renew an ssl i get this error
`Error: Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: Traceback (most recent call last):
File &quot;/opt/psa/var/modules/letsencrypt/venv/bin/letsencrypt&quot;, line 11, in &lt;module&gt;
sys.exit(main())
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.Abkt1/local/lib/python2.7/site-packages/letsencrypt/cli.py&quot;, line 1950, in main
plugins = plugins_disco.PluginsRegistry.find_all()
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.Abkt1/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py&quot;, line 168, in find_all
plugin_ep = PluginEntryPoint(entry_point)
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.Abkt1/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py&quot;, line 31, in __init__
self.plugin_cls = entry_point.load()
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.Abkt1/local/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 2201, in load
self.require(*args, **kwargs)
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.Abkt1/local/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 2218, in require
items = working_set.resolve(reqs, env, installer)
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.Abkt1/local/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 835, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (cryptography 1.1 (/opt/psa/var/modules/letsencrypt/venv.Abkt1/lib/python2.7/site-packages), Requirement.parse('cryptography&gt;=1.3'), set(['PyOpenSSL']))`

**Comment by TheNephilim88** [comment]
Same here with CentOS Linux 7.2.1511

**Comment by mv-T** [comment]
hi,

check if python-dev, build-essential and libffi-dev is installed.

if this is ok so u should upgrade the cffi and cryptography module by pip.

`source /opt/psa/var/modules/letsencrypt/venv.**Abkt1**/bin/activate
pip install --upgrade cffi
pip install --upgrade cryptography`

Attention! Look at ur own Error Message for the sourc path "venv.******"!

I hope this can help someone.

**Comment by TheNephilim88** [comment]
Thanks worked now.

But I also needed to install openssl-devel (on CentOS, for Ubuntu libssl-dev)

**Comment by immist** [comment]
Same here on Ubuntu 14.04, but the following commands don't seem to fix the error:
```

source /opt/psa/var/modules/letsencrypt/venv.Abkt1/bin/activate
pip install --upgrade cffi
pip install --upgrade cryptography
sudo apt-get install build-essential libssl-dev libffi-dev python-dev
```

**Comment by mv-T** [comment]
have u changed the source path to this one at ur error log?(/opt/psa/var/modules/letsencrypt/venv.????/bin/activate)

**Comment by TheNephilim88** [comment]
Did you change "venv.Abkt1" to the one yours is named? Also check if the folder is correct. For me, on CentOS, the folder was different, but simply check the error log, there you will see the correct folder including venv.-id

**Comment by LairdWalker** [comment]
i have did everything in this list but its still the same on Ubuntu 14.04.4

sudo apt-get install build-essential libssl-dev libffi-dev python-dev (shows all installed)
source /opt/psa/var/modules/letsencrypt/venv.Abkt1/bin/activate (edited thevenv.Abkt1 name )
pip install --upgrade cffi (installed )
pip install --upgrade cryptography (installed)

all commands worked fine and also edited 
source /opt/psa/var/modules/letsencrypt/venv.xxxx/bin/activate rebooted the server and still the

same error

i will just install the ssl manually for now thanks

**Comment by gnanet** [comment]
I dont know if this is letter to letter tha sam but i got the following on a fresh upgraded from 12.0.18 to 12.5.30  Debian 7.9 while requesting the first cert ever on this machine:

> Error: Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: Traceback (most recent call last):
File &quot;/opt/psa/var/modules/letsencrypt/venv/bin/letsencrypt&quot;, line 11, in &lt;module&gt;
sys.exit(main())
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.rzEMc/local/lib/python2.7/site-packages/letsencrypt/cli.py&quot;, line 1950, in main
plugins = plugins_disco.PluginsRegistry.find_all()
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.rzEMc/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py&quot;, line 168, in find_all
plugin_ep = PluginEntryPoint(entry_point)
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.rzEMc/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py&quot;, line 31, in __init__
self.plugin_cls = entry_point.load()
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.rzEMc/local/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 2201, in load
self.require(*args, **kwargs)
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.rzEMc/local/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 2218, in require
items = working_set.resolve(reqs, env, installer)
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.rzEMc/local/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 835, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (cryptography 1.1 (/opt/psa/var/modules/letsencrypt/venv.rzEMc/lib/python2.7/site-packages), Requirement.parse('cryptography&gt;=1.3'), set(['PyOpenSSL']))

**Comment by gnanet** [comment]
Applied on my case (the venv path is different)
This worked on **Debian 7.9 with Plesk 12.5.30 MU26 and Let's Encrypt Extension 1.5**
`sudo apt-get install build-essential libssl-dev libffi-dev python-dev`
`source /usr/local/psa/var/modules/letsencrypt/venv.rzEMc/bin/activate`
`pip install --upgrade cffi`
`pip install --upgrade cryptography`
After these succeed, i could request the cert again, and now everything went OK

**Comment by miguelitos** [comment]
Centos 6.6
`yum install gcc libffi-devel python-devel openssl-devel`
'source /usr/local/psa/var/modules/letsencrypt/venv.XYZ/bin/activate'
'pip install --upgrade cffi'
'pip install --upgrade cryptography'

**Comment by xgin** [comment]
The issue is caused by the latest release of pyOpenSSL: it requires the dependency newer then we provide.
We will restrict pyOpenSSL==0.15.1 today until the dependent packages are prepared in our repository.

**Comment by lucer** [comment]
We updated cffi to 1.5.2 and cryptography to 1.3.1, you need to reinstall the extension, or re-run /usr/local/psa/admin/bin/modules/letsencrypt/le-installer

**Comment by LairdWalker** [comment]
confirmed working with 	
Ubuntu 14.04.4 LTS & Plesk v12.5.30_build1205150826.19
Thanks guys
