### ISSUE TITLE
ContextualVersionConflict: (cryptography 1.1 (/usr/local/psa/var/modules/letsencrypt/venv.HOXM6/lib/python2.6/site-packages), Requirement.parse('cryptography&gt;=1.3'), set(['PyOpenSSL']))

### ISSUE THREAD

**Issue by rorteu** [plesk/letsencrypt-plesk#88]
Hi,

I have CentOS 6.6 and plesk letsencrypt version 1.5, when I try to install a certificate on a domain I obtain the following error:

ContextualVersionConflict: (cryptography 1.1 (/usr/local/psa/var/modules/letsencrypt/venv.HOXM6/lib/python2.6/site-packages), Requirement.parse('cryptography&gt;=1.3'), set(['PyOpenSSL']))

May It be related to Openssl versión? I have installed openssl-1.0.1e-30.el6_6.5

Thanks,
Rafa Orteu.

**Comment by lucer** [comment]
We updated cffi to 1.5.2 and cryptography to 1.3.1, you need to reinstall the extension, or re-run /usr/local/psa/admin/bin/modules/letsencrypt/le-installer

**Comment by rorteu** [comment]
Thank you very much indeed for the response.

**Comment by Gallenkamp** [comment]
Holy Cow! THIS is the only thing that worked for me. I searched about 6 hours actively, installing stuff, searching for broken dependencies, upgrading whatever was needed. Many lose ends, non of them with a proper result.
