### ISSUE TITLE
installation from extension catalog 

### ISSUE THREAD

**Issue by iamkingsleyf** [plesk/letsencrypt-plesk#89]
Hello;

I am trying to install letsencrypt 1.5 from the extension catalog but am having issues doing that because of the below error.

Error: Failed to install the extension: Executing /opt/psa/admin/plib/modules/letsencrypt/scripts/post-install.php failed: Bootstrapping dependencies for ubuntu trusty... E: Failed to fetch http://autoinstall.plesk.com/ubuntu/LETSENCRYPT_0.0.1/../../LETSENCRYPT_0.0.1/dist-deb-Ubuntu-14.04-x86_64/packages/plesk-wheel-cffi_1.5.2-ubuntu14.04.16032214_amd64.deb 404 Not Found E: Failed to fetch http://autoinstall.plesk.com/ubuntu/LETSENCRYPT_0.0.1/../../LETSENCRYPT_0.0.1/dist-deb-Ubuntu-14.04-x86_64/packages/plesk-wheel-cryptography_1.3.1-ubuntu14.04.16032212_amd64.deb 404 Not Found E: Failed to fetch http://autoinstall.plesk.com/ubuntu/LETSENCRYPT_0.0.1/../../LETSENCRYPT_0.0.1/dist-deb-Ubuntu-14.04-x86_64/packages/plesk-letsencrypt-pre_1.0.0-ubuntu14.04.16032214_amd64.deb 404 Not Found E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by azerusDE** [comment]
Same here with Plesk 12.5 on Ubuntu 14.04

**Comment by iamkingsleyf** [comment]
Try adding this to **/etc/hosts** then restart plesk panel `199.115.104.31 pleskwin.download.swsoft.com download1.parallels.com autoinstall.plesk.com origin.autoinstall.plesk.com`

**Comment by lucer** [comment]
The problem caused by invalid configuration of repository on autoinstall.plesk.com, and now resolved
