### ISSUE TITLE
Can't remove certificate

### ISSUE THREAD

**Issue by maxxscho** [plesk/letsencrypt-plesk#94]
Hi - great extension!!

Maybe I'm missing something, but I can't delete a certificate from a domain. Tried Let's Encrypt on one of my "test"-domains and now I can't remove it. The checkbox is grayed out.
![screenshot 2016-04-11 10 46 12](https://cloud.githubusercontent.com/assets/543690/14421557/a8254cae-ffd2-11e5-91d8-4062c90c4f3f.png)

**Comment by xgin** [comment]
A certificate cannot be deleted while it is in use.
In `Hosting Settings` of your domain you can select another, e.g. `default certificate`
![choose-default-cert](https://cloud.githubusercontent.com/assets/5378093/14423222/7c5a11ac-fffc-11e5-809a-7f33489a1227.png)

**Comment by maxxscho** [comment]
Hi @xgin!!!

Thx a lot - didn't know this 😊 !!
